import { 
  Project, 
  Opportunity, 
  CourseModule, 
  InfrastructureFacility, 
  FeedPost, 
  StartupEntity, 
  BusinessEntity,
  ResearchPaper,
  NotificationItem, 
  UserProfile 
} from './types';

export const INITIAL_USER: UserProfile = {
  id: 'usr-001',
  name: 'Zaman',
  handle: '@zaman',
  role: 'student',
  headline: 'Builder | Learner | Innovator • Robotics & Embedded Systems',
  avatar: '/assets/images/tech_robotics_01.jpg',
  coverImage: '/assets/images/hero_dashboard_banner.jpg',
  bio: 'Passionate about robotics, embedded systems, and building real solutions for planetary and terrestrial exploration. Open to collaborate on robotics, autonomous navigation, and IoT.',
  location: 'Delhi, India',
  verificationLevel: 2,
  organization: 'Indian Institute of Technology Delhi',
  skills: ['Robotics', 'AI / ML', 'ROS', 'Python', 'C++', 'Embedded Systems', 'Computer Vision', 'PCB Design'],
  learningProgress: 68,
  stats: {
    projects: 4,
    contributions: 18,
    skillsCount: 12,
    certificates: 3,
    opportunitiesCount: 5,
  },
  portfolios: {
    personal: true,
    startups: ['HydroSense Labs', 'AgriMesh'],
    businesses: ['RoboKart'],
    research: ['Autonomous Terrain Navigation Grant'],
    facilities: ['IIT Delhi Maker-pass']
  }
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-01',
    code: 'CH-PROJ-ROVER-2025',
    title: 'Autonomous Rover',
    tagline: 'An AI-powered rover for planetary exploration and research.',
    description: 'This project aims to design and develop an autonomous rover capable of navigating challenging terrains for planetary exploration. It integrates AI-based navigation, sensor fusion, and real-time data analysis to support research missions on Mars and the Moon.',
    problemStatement: 'Off-world terrain mapping requires real-time sub-meter navigation resilience without human teleoperation delays.',
    objective: 'Deploy a tested prototype equipped with stereoscopic visual odometry, ROS2 control stack, and 6-wheel rocker-bogie suspension.',
    category: 'Robotics',
    stage: 'Prototype',
    progress: 72,
    owner: {
      name: 'Zaman',
      avatar: '/assets/images/tech_robotics_01.jpg',
      role: 'Project Lead',
      organization: 'IIT Delhi'
    },
    location: 'Delhi, India',
    timeline: 'Expected Completion Dec 2025',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Robotics', 'AI', 'Embedded Systems', 'Computer Vision', 'Mechanical Engineering'],
    currentContributors: 8,
    maxContributors: 15,
    openTasksCount: 5,
    verified: true,
    coverImage: '/assets/images/card_robotics_intern.jpg',
    views: 4850,
    stars: 96,
    createdAt: '2025-03-10',
    tasks: [
      {
        id: 'task-1',
        title: 'Computer Vision: Stereoscopic Depth Map SLAM Tuning',
        description: 'Implement real-time obstacle disparity computation using OpenCV and CUDA acceleration on Jetson Orin Nano.',
        category: 'AI / Vision',
        status: 'In Progress',
        priority: 'Critical',
        rewardTier: 'Tier 4',
        assignee: {
          name: 'Zaman',
          avatar: '/assets/images/tech_robotics_01.jpg'
        },
        skillsRequired: ['OpenCV', 'CUDA', 'Python', 'ROS2'],
        dueDate: '2026-09-28'
      },
      {
        id: 'task-2',
        title: 'Mechanical: Rocker-Bogie Suspension Stress Testing in Sand Pit',
        description: 'Fabricate carbon fiber reinforced nylon joints and evaluate tilt stability on 35-degree loose gravel inclines.',
        category: 'Mechanical',
        status: 'Open',
        priority: 'High',
        rewardTier: 'Tier 3',
        skillsRequired: ['SolidWorks', '3D Printing', 'Stress Analysis'],
        dueDate: '2026-10-05'
      },
      {
        id: 'task-3',
        title: 'Firmware: Motor Controller CAN-Bus Telemetry Packets',
        description: 'Encode brushless motor encoder positions and temperature telemetry into 1Mbps CAN-FD frames.',
        category: 'Embedded',
        status: 'Open',
        priority: 'Medium',
        rewardTier: 'Tier 3',
        skillsRequired: ['C++', 'CAN-Bus', 'STM32'],
        dueDate: '2026-10-12'
      },
      {
        id: 'task-4',
        title: 'Documentation: Open Hardware Replication & Bill of Materials',
        description: 'Document standard off-the-shelf fasteners, bearings, motor models, and assembly checklist.',
        category: 'Documentation',
        status: 'Open',
        priority: 'Low',
        rewardTier: 'Tier 2',
        skillsRequired: ['Markdown', 'Git', 'BOM Management'],
        dueDate: '2026-10-20'
      }
    ],
    contributors: [
      {
        id: 'c-1',
        name: 'Zaman',
        role: 'Project Lead',
        avatar: '/assets/images/tech_robotics_01.jpg',
        contributionsCount: 42,
        level: 2,
        joinedDate: 'Mar 2025'
      },
      {
        id: 'c-2',
        name: 'Priya Sharma',
        role: 'AI / Navigation Lead',
        avatar: '/assets/images/tech_ai_03.jpg',
        contributionsCount: 28,
        level: 3,
        joinedDate: 'Apr 2025'
      },
      {
        id: 'c-3',
        name: 'Arjun Mehta',
        role: 'Embedded Systems',
        avatar: '/assets/images/tech_circuit_02.jpg',
        contributionsCount: 19,
        level: 3,
        joinedDate: 'May 2025'
      },
      {
        id: 'c-4',
        name: 'Riya Verma',
        role: 'Mechanical CAD',
        avatar: '/assets/images/tech_manufacturing_04.jpg',
        contributionsCount: 14,
        level: 2,
        joinedDate: 'Jun 2025'
      },
      {
        id: 'c-5',
        name: 'Karan Singh',
        role: 'Computer Vision',
        avatar: '/assets/images/tech_robotics_05.jpg',
        contributionsCount: 11,
        level: 2,
        joinedDate: 'Jul 2025'
      },
      {
        id: 'c-6',
        name: 'Ananya Rao',
        role: 'Sensor Fusion',
        avatar: '/assets/images/tech_biotech_02.jpg',
        contributionsCount: 8,
        level: 4,
        joinedDate: 'Aug 2025'
      }
    ],
    files: [
      { id: 'f-1', name: 'autonomous_rover_chassis_cad.step', size: '24.5 MB', type: '3D CAD', updatedAt: 'Yesterday', uploadedBy: 'Riya Verma' },
      { id: 'f-2', name: 'stereoscopic_slam_node.py', size: '42 KB', type: 'CODE', updatedAt: '3 days ago', uploadedBy: 'Zaman' },
      { id: 'f-3', name: 'mainboard_pcb_gerbers_v3.zip', size: '4.8 MB', type: 'PCB', updatedAt: '1 week ago', uploadedBy: 'Arjun Mehta' },
      { id: 'f-4', name: 'field_test_mars_yard_report.pdf', size: '6.2 MB', type: 'REPORT', updatedAt: '2 weeks ago', uploadedBy: 'Zaman' },
      { id: 'f-5', name: 'rover_schematics_revB.kicad_sch', size: '1.9 MB', type: 'SCHEMATIC', updatedAt: '2 weeks ago', uploadedBy: 'Arjun Mehta' }
    ]
  },
  {
    id: 'proj-02',
    code: 'CH-PROJ-PCB-2025',
    title: 'Low-Cost PCB Fabrication',
    tagline: 'Developing an affordable PCB prototyping solution for students.',
    description: 'An open-source desktop milling and chemical etching workstation enabling makers to fabricate rapid double-sided surface mount circuit boards in under 45 minutes.',
    problemStatement: 'International PCB prototyping cycles take 10-14 days and high customs duties, halting academic engineering iterations.',
    objective: 'Enable 6-mil trace width in-house desktop PCB fabrication with open-source toolpath generation.',
    category: 'Hardware',
    stage: 'Open',
    progress: 45,
    owner: {
      name: 'Vikram Patel',
      avatar: '/assets/images/tech_energy_04.jpg',
      role: 'Lab Director',
      organization: 'Makerspace Bengaluru'
    },
    location: 'Bengaluru, India',
    timeline: '4 months remaining',
    skillLevel: 'Beginner - Intermediate',
    visibility: 'Open Source',
    isPhysical: true,
    requiredSkills: ['Hardware', 'PCB', 'Manufacturing', 'KiCAD', 'CNC'],
    currentContributors: 5,
    maxContributors: 10,
    openTasksCount: 4,
    verified: true,
    coverImage: '/assets/images/card_pcb_design.jpg',
    views: 3200,
    stars: 82,
    createdAt: '2025-05-12',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-03',
    code: 'CH-PROJ-AGRI-2025',
    title: 'Smart Agriculture System',
    tagline: 'IoT-based monitoring system for precision farming.',
    description: 'Autonomous soil moisture, canopy temperature, and NPK nutrient sensors paired with solar drip irrigation actuators for arid crop yields.',
    problemStatement: 'Over-irrigation in Punjab aquifers has depleted water tables by 4 meters over 5 years while wasting fertilizer runoff.',
    objective: 'Deploy 80 wireless sensor nodes powered by supercapacitors in wheat and mustard farms.',
    category: 'Electronics',
    stage: 'Active',
    progress: 30,
    owner: {
      name: 'Dr. Gurpreet Singh',
      avatar: '/assets/images/tech_biotech_01.jpg',
      role: 'Agritech Lead',
      organization: 'PAU Ludhiana'
    },
    location: 'Punjab, India',
    timeline: '6 months remaining',
    skillLevel: 'Intermediate',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['IoT', 'Agriculture', 'Sensors', 'LoRaWAN', 'Solar Harvesting'],
    currentContributors: 11,
    maxContributors: 20,
    openTasksCount: 6,
    verified: true,
    coverImage: '/assets/images/card_smart_agriculture.jpg',
    views: 2980,
    stars: 114,
    createdAt: '2025-04-18',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-04',
    code: 'CH-PROJ-BIONIC-2025',
    title: 'Bionic Hand Prototype',
    tagline: 'Affordable and functional prosthetic hand using 3D printing.',
    description: 'Myoelectric prosthetic with tendon-driven fingers, compliant silicone fingertips, and tactile pressure feedback for amputees.',
    problemStatement: 'Children outgrow expensive medical prosthetics annually, leaving thousands without assistive devices.',
    objective: 'Fabricate modular parametric hands in standard PLA/PETG with interchangeable socket geometry under ₹12,000.',
    category: 'Robotics',
    stage: 'Active',
    progress: 60,
    owner: {
      name: 'BioHeal Labs',
      avatar: '/assets/images/tech_robotics_02.jpg',
      role: 'Biomechanics Director',
      organization: 'BioHeal Foundation'
    },
    location: 'Hyderabad, India',
    timeline: '3 months remaining',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Healthcare', '3D Printing', 'Design', 'EMG Processing', 'Embedded C'],
    currentContributors: 7,
    maxContributors: 12,
    openTasksCount: 3,
    verified: true,
    coverImage: '/assets/images/card_3d_printing.jpg',
    views: 4120,
    stars: 148,
    createdAt: '2025-03-24',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-05',
    code: 'CH-PROJ-ENERGY-2025',
    title: 'Hybrid Renewable Energy System',
    tagline: 'Integrated solar and wind solution for rural areas.',
    description: 'Micro-scale vertical axis wind turbine coupled with bifacial solar panels and MPPT battery bank designed for coastal and off-grid villages.',
    problemStatement: 'Monsoon coastal conditions cause prolonged solar grid blackouts while wind generation remains underutilized.',
    objective: 'Demonstrate continuous 1.5kW clean power generation throughout tropical storm seasons.',
    category: 'CleanTech',
    stage: 'Open',
    progress: 25,
    owner: {
      name: 'Kavita Chawla',
      avatar: '/assets/images/tech_energy_01.jpg',
      role: 'Clean Energy Researcher',
      organization: 'IIT Madras Energy Lab'
    },
    location: 'Chennai, India',
    timeline: '8 months remaining',
    skillLevel: 'All Levels',
    visibility: 'Open Source',
    isPhysical: true,
    requiredSkills: ['Energy', 'Sustainability', 'Hardware', 'Power Electronics', 'Inverter Design'],
    currentContributors: 9,
    maxContributors: 18,
    openTasksCount: 7,
    verified: true,
    coverImage: '/assets/images/card_wind_solar_hybrid.jpg',
    views: 2430,
    stars: 92,
    createdAt: '2025-06-01',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-06',
    code: 'CH-PROJ-NANO-2025',
    title: 'Nano-Material Research',
    tagline: 'Exploring nano-materials for next-gen electronics.',
    description: 'Synthesizing two-dimensional molybdenum disulfide (MoS2) and graphene heterostructures for ultra-low power neuromorphic synaptic transistors.',
    problemStatement: 'Silicon CMOS scaling reaches physical tunneling barriers, requiring 2D atomic semiconductors for sub-1nm gates.',
    objective: 'Publish open dataset of chemical vapor deposition parameters and high-mobility I-V characteristics.',
    category: 'Research',
    stage: 'Active',
    progress: 40,
    owner: {
      name: 'Dr. Meera Iyer',
      avatar: '/assets/images/tech_lab_01.jpg',
      role: 'Principal Investigator',
      organization: 'IISc Materials Science'
    },
    location: 'IIT Delhi, India',
    timeline: '10 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Research', 'Materials', 'Semiconductor', 'AFM Analysis', 'Cleanroom Protocols'],
    currentContributors: 6,
    maxContributors: 10,
    openTasksCount: 4,
    verified: true,
    coverImage: '/assets/images/card_nanomaterials_research.jpg',
    views: 3890,
    stars: 165,
    createdAt: '2025-02-14',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-07',
    code: 'CH-PROJ-DRONE-2025',
    title: 'Disaster Relief Drone',
    tagline: 'Drones for disaster mapping and supply delivery.',
    description: 'Long-range VTOL (Vertical Take-off & Landing) autonomous drone payload delivery system engineered for flash floods and Himalayan terrain relief.',
    problemStatement: 'Mountainous landslides cut off road access to remote villages during monsoons, delaying essential medicine delivery.',
    objective: 'Achieve 3kg payload delivery across 40km round-trip in sub-zero alpine conditions with thermal survivor detection.',
    category: 'Hardware',
    stage: 'Active',
    progress: 80,
    owner: {
      name: 'Aarav Singh',
      avatar: '/assets/images/tech_robotics_03.jpg',
      role: 'Avionics Engineer',
      organization: 'AeroSky Labs'
    },
    location: 'Uttarakhand, India',
    timeline: '1 month remaining',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Drones', 'Computer Vision', 'Logistics', 'ArduPilot', 'Aerodynamics'],
    currentContributors: 12,
    maxContributors: 15,
    openTasksCount: 2,
    verified: true,
    coverImage: '/assets/images/card_drone_swarm.jpg',
    views: 5120,
    stars: 230,
    createdAt: '2025-01-20',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-08',
    code: 'CH-PROJ-AILRN-2025',
    title: 'AI Learning Platform',
    tagline: 'An open platform for personalized skill development.',
    description: 'Adaptive open-source knowledge graph recommending customized STEM hands-on project pathways based on learner skill gaps and hardware availability.',
    problemStatement: 'Generic online MOOCs have sub-10% completion rates due to lack of physical project integration.',
    objective: 'Generate personalized learning roadmaps tied to real open-hardware repository contributions.',
    category: 'AI / ML',
    stage: 'Open',
    progress: 50,
    owner: {
      name: 'LearnLoop Team',
      avatar: '/assets/images/tech_ai_04.jpg',
      role: 'Core Contributors',
      organization: 'LearnLoop'
    },
    location: 'Remote',
    timeline: '5 months remaining',
    skillLevel: 'Beginner - Intermediate',
    visibility: 'Open Source',
    isPhysical: false,
    requiredSkills: ['AI', 'Education', 'Web App', 'React', 'Node.js', 'LLM Tuning'],
    currentContributors: 14,
    maxContributors: 25,
    openTasksCount: 8,
    verified: true,
    coverImage: '/assets/images/card_aiml_developer.jpg',
    views: 3450,
    stars: 128,
    createdAt: '2025-05-02',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-09',
    code: 'CH-PROJ-SORT-2025',
    title: 'AI Based Sorting Arm',
    tagline: 'Computer vision and robotic manipulation for automated factory recycling.',
    description: 'High-speed Delta robot mechanism utilizing RGB-D depth perception and edge neural inference to sort municipal plastic polymers at 90 picks per minute.',
    problemStatement: 'Manual waste segregation exposes workers to hazardous materials while maintaining low throughput and contamination.',
    objective: 'Sort PET, HDPE, and PP plastics with 97% purity using lightweight on-premise vision models.',
    category: 'Robotics',
    stage: 'Active',
    progress: 65,
    owner: {
      name: 'Rakesh Verma',
      avatar: '/assets/images/tech_manufacturing_04.jpg',
      role: 'Mechatronics Lead',
      organization: 'TechFab Maharashtra'
    },
    location: 'Pune, India',
    timeline: '3 months remaining',
    skillLevel: 'Intermediate',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['AI', 'Computer Vision', 'Robotics', 'Delta Kinematics', 'YOLOv10'],
    currentContributors: 7,
    maxContributors: 12,
    openTasksCount: 4,
    verified: true,
    coverImage: '/assets/images/card_manufacturing_intern.jpg',
    views: 3120,
    stars: 141,
    createdAt: '2025-04-10',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-10',
    code: 'CH-PROJ-QUANT-2025',
    title: 'Cryogenic Quantum Qubit Processor',
    tagline: 'Sub-Kelvin superconducting transmon qubit control hardware & RF microwave filters.',
    description: 'Development of cryogenic microwave attenuators, non-magnetic coaxial cables, and FPGA-based pulse synthesis for high-fidelity multi-qubit gate operations.',
    problemStatement: 'Thermal microwave noise in dilution refrigerators reduces quantum coherence time to sub-10 microseconds.',
    objective: 'Demonstrate 99.4% two-qubit randomized benchmarking fidelity with custom cryogenic PCB filters.',
    category: 'Research',
    stage: 'Active',
    progress: 55,
    owner: {
      name: 'Dr. Srinivas Rao',
      avatar: '/assets/images/tech_lab_02.jpg',
      role: 'Lead Scientist',
      organization: 'TIFR / IISc'
    },
    location: 'Bengaluru, India',
    timeline: '7 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Quantum Physics', 'RF Microwave', 'Cryogenics', 'FPGA', 'Python Qiskit'],
    currentContributors: 9,
    maxContributors: 15,
    openTasksCount: 5,
    verified: true,
    coverImage: '/assets/images/card_quantum_computing.jpg',
    views: 4210,
    stars: 189,
    createdAt: '2025-03-01',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-11',
    code: 'CH-PROJ-EV-2025',
    title: 'Autonomous Modular EV Skateboard',
    tagline: 'Open-architecture steer-by-wire electric vehicle platform with regenerative braking.',
    description: 'Modular chassis for commercial intra-city cargo shuttles featuring 400V battery pack, dual PMSM hub motors, and CAN-FD autonomous drive actuators.',
    problemStatement: 'Custom EV conversions lack standardized open drive-by-wire hardware interfaces for autonomous navigation retrofits.',
    objective: 'Provide open mechanical and CAN bus specifications for plug-and-play autonomous shuttle integration.',
    category: 'CleanTech',
    stage: 'Active',
    progress: 78,
    owner: {
      name: 'Arjun Deshmukh',
      avatar: '/assets/images/tech_manufacturing_05.jpg',
      role: 'EV Powertrain Architect',
      organization: 'Pune Mobility Labs'
    },
    location: 'Pune, India',
    timeline: '2 months remaining',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Automotive', 'Power Electronics', 'BMS', 'CAN-Bus', 'Suspension Design'],
    currentContributors: 14,
    maxContributors: 20,
    openTasksCount: 3,
    verified: true,
    coverImage: '/assets/images/card_autonomous_ev.jpg',
    views: 5670,
    stars: 275,
    createdAt: '2025-01-15',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-12',
    code: 'CH-PROJ-CRISPR-2025',
    title: 'Microfluidic CRISPR Gene Synthesizer',
    tagline: 'Automated benchtop microfluidic biochip for targeted genomic payload synthesis.',
    description: 'PDMS elastomer micro-channels and piezoelectric droplet generators for high-throughput enzymatic Cas13 ribonucleoprotein synthesis.',
    problemStatement: 'Custom guide RNA delivery protocols are cost-prohibitive and take weeks in commercial centralized facilities.',
    objective: 'Enable point-of-care programmable gRNA droplet generation under 4 hours.',
    category: 'Research',
    stage: 'Open',
    progress: 38,
    owner: {
      name: 'Dr. Ananya Roy',
      avatar: '/assets/images/tech_biotech_02.jpg',
      role: 'Synthetic Biologist',
      organization: 'C-CAMP Bengaluru'
    },
    location: 'Bengaluru, India',
    timeline: '9 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Microfluidics', 'CRISPR', 'Biomedical', 'PDMS Lithography', 'Python'],
    currentContributors: 6,
    maxContributors: 12,
    openTasksCount: 4,
    verified: true,
    coverImage: '/assets/images/card_biotech_crispr.jpg',
    views: 3180,
    stars: 154,
    createdAt: '2025-04-20',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-13',
    code: 'CH-PROJ-SAT-2025',
    title: 'LEO Swarm CubeSat Subsystems',
    tagline: 'Radiation-hardened power conditioning and inter-satellite laser communication terminal.',
    description: '1U CubeSat form-factor payload incorporating gallium arsenide solar panels, magnetorquers, and 100Mbps optical inter-satellite communication links.',
    problemStatement: 'Academic nanosatellites struggle with bandwidth bottlenecks over congested UHF/VHF ground station passes.',
    objective: 'Establish verified optical downlink and orbit altitude station-keeping across 3 prototype cubesats.',
    category: 'Hardware',
    stage: 'Active',
    progress: 82,
    owner: {
      name: 'Rohan Joshi',
      avatar: '/assets/images/tech_space_01.jpg',
      role: 'Aerospace Lead',
      organization: 'ISRO-Linked Space Core'
    },
    location: 'Thiruvananthapuram, India',
    timeline: '4 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Aerospace', 'Optical Comms', 'Orbital Mechanics', 'Embedded C', 'Solar MPPT'],
    currentContributors: 16,
    maxContributors: 22,
    openTasksCount: 5,
    verified: true,
    coverImage: '/assets/images/card_satellite_project.jpg',
    views: 6420,
    stars: 310,
    createdAt: '2025-02-05',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-14',
    code: 'CH-PROJ-CHIP-2025',
    title: 'Edge Neuromorphic AI Accelerator',
    tagline: 'Custom RISC-V tensor core taped out in 28nm for low-power drone perception.',
    description: 'Open-source silicon accelerator utilizing spiking neural network (SNN) weights to perform 120 FPS object classification within 1.8 Watts.',
    problemStatement: 'Commercial GPU cores consume excessive battery power on lightweight disaster response quadcopters.',
    objective: 'Tape-out GDSII silicon verified with open-source SkyWater and Efabless toolchains.',
    category: 'Electronics',
    stage: 'Active',
    progress: 70,
    owner: {
      name: 'Dr. Vivek Menon',
      avatar: '/assets/images/tech_circuit_01.jpg',
      role: 'VLSI Architect',
      organization: 'IIT Madras'
    },
    location: 'Chennai, India',
    timeline: '3 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Open Source',
    isPhysical: true,
    requiredSkills: ['VLSI', 'Verilog', 'RISC-V', 'OpenLane', 'Spiking Neurons'],
    currentContributors: 11,
    maxContributors: 18,
    openTasksCount: 4,
    verified: true,
    coverImage: '/assets/images/card_ai_neural_processor.jpg',
    views: 4980,
    stars: 224,
    createdAt: '2025-03-18',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-15',
    code: 'CH-PROJ-OPTICS-2025',
    title: 'Deep Space Optical Transceiver',
    tagline: 'Gigabit laser communications terminal for low-Earth orbit satellites.',
    description: 'High-speed pulsed laser transmitter with fine beam steering piezo actuators and avalanche photodiode receivers.',
    problemStatement: 'RF downlink bandwidth is bottlenecked at 100 Mbps for hyper-spectral earth observation data.',
    objective: 'Demonstrate 1.25 Gbps downlink over 1,000 km ground-station optical path.',
    category: 'SpaceTech',
    stage: 'Active',
    progress: 55,
    owner: {
      name: 'Dr. Alok Sen',
      avatar: '/assets/images/tech_space_04.jpg',
      role: 'Principal Investigator',
      organization: 'ISRO Telemetry Node'
    },
    location: 'Thiruvananthapuram, India',
    timeline: '5 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Photonics', 'Optics', 'DSP', 'FPGA', 'Piezo'],
    currentContributors: 9,
    maxContributors: 15,
    openTasksCount: 4,
    verified: true,
    coverImage: '/assets/images/tech_space_03.jpg',
    views: 4120,
    stars: 175,
    createdAt: '2025-06-01',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-16',
    code: 'CH-PROJ-H2-2025',
    title: 'High-Density Hydrogen Fuel Cell Stack',
    tagline: 'Proton-exchange membrane fuel cells for lightweight drones.',
    description: 'Compact 2kW PEM fuel cell system with carbon-wrapped hydrogen storage tanks delivering 4x the endurance of lithium batteries.',
    problemStatement: 'Heavy drone payloads reduce battery flight times below 25 minutes for humanitarian relief missions.',
    objective: 'Achieve 3 hours continuous hovering flight with a 3kg payload.',
    category: 'CleanTech',
    stage: 'Active',
    progress: 40,
    owner: {
      name: 'Dr. Sunita Deshmukh',
      avatar: '/assets/images/tech_energy_09.jpg',
      role: 'Energy Systems Fellow',
      organization: 'IIT Roorkee Energy Lab'
    },
    location: 'Roorkee, India',
    timeline: '7 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['FuelCells', 'Hydrogen', 'Thermodynamics', 'Flow Simulation'],
    currentContributors: 7,
    maxContributors: 12,
    openTasksCount: 5,
    verified: true,
    coverImage: '/assets/images/tech_energy_07.jpg',
    views: 3450,
    stars: 128,
    createdAt: '2025-06-15',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-17',
    code: 'CH-PROJ-ROV-2025',
    title: 'Autonomous Heavy Submersible ROV',
    tagline: 'Deep-sea tetherless exploration robot with acoustic positioning.',
    description: 'Marine ROV rated for 500-meter depth featuring 8 magnetic-coupling thrusters, ultra-short baseline (USBL) acoustic tracking, and robotic sample grabber.',
    problemStatement: 'Commercial deep-water benthic mapping tools are prohibitively costly for oceanography universities.',
    objective: 'Design an open modular submarine chassis with real-time stereoscopic seafloor SLAM.',
    category: 'Robotics',
    stage: 'Active',
    progress: 68,
    owner: {
      name: 'Karan Mehra',
      avatar: '/assets/images/tech_circuit_09.jpg',
      role: 'Marine Mechatronics Lead',
      organization: 'National Institute of Ocean Tech'
    },
    location: 'Goa, India',
    timeline: '3 months remaining',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Open Source',
    isPhysical: true,
    requiredSkills: ['Marine Robotics', 'ROS2', 'Pressure Vessels', 'Acoustics'],
    currentContributors: 12,
    maxContributors: 20,
    openTasksCount: 6,
    verified: true,
    coverImage: '/assets/images/tech_robotics_09.jpg',
    views: 4890,
    stars: 210,
    createdAt: '2025-05-20',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-18',
    code: 'CH-PROJ-NPU-2025',
    title: 'Deep Neural Edge Quantization Benchmark',
    tagline: 'Hardware-aware compiler & accelerator profiling for open RISC-V silicon.',
    description: 'Open-source TVM runtime optimizer mapping transformer attention heads onto custom 4-bit tensor systolic cores.',
    problemStatement: 'Standard edge inference toolchains produce sub-optimal utilization on domain-specific academic accelerators.',
    objective: 'Automate hardware operator synthesis yielding 85% MAC utilization on RISC-V vector extensions.',
    category: 'Hardware',
    stage: 'Open',
    progress: 75,
    owner: {
      name: 'Arjun Swaminathan',
      avatar: '/assets/images/tech_ai_08.jpg',
      role: 'Compiler Engineer',
      organization: 'Open-Silicon Initiative'
    },
    location: 'Chennai, India',
    timeline: '2 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Open Source',
    isPhysical: false,
    requiredSkills: ['RISC-V', 'LLVM', 'TVM', 'Verilog', 'PyTorch'],
    currentContributors: 15,
    maxContributors: 25,
    openTasksCount: 8,
    verified: true,
    coverImage: '/assets/images/tech_ai_10.jpg',
    views: 5670,
    stars: 285,
    createdAt: '2025-04-10',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-19',
    code: 'CH-PROJ-GLUCOSE-2025',
    title: 'Continuous Glucose Bio-Impedance Sensor',
    tagline: 'Non-invasive microneedle wearable for painless metabolic monitoring.',
    description: 'Biocompatible polymer micro-array patch with enzymatic carbon-paste electrodes coupled to a BLE analog front-end for 14-day continuous interstitial tracking.',
    problemStatement: 'Fingerstick blood tests are painful and discourage frequent glycemic index monitoring in diabetic patients.',
    objective: 'Manufacture disposable ₹200 microneedle strips with 0.98 Pearson correlation to venous blood reference.',
    category: 'Hardware',
    stage: 'Active',
    progress: 50,
    owner: {
      name: 'Dr. Malini Roy',
      avatar: '/assets/images/tech_biotech_08.jpg',
      role: 'Biomaterials Scientist',
      organization: 'IISc Centre for BioSystems'
    },
    location: 'Bengaluru, India',
    timeline: '6 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['BioSensors', 'Microfluidics', 'BLE', 'Electrochemistry'],
    currentContributors: 8,
    maxContributors: 16,
    openTasksCount: 5,
    verified: true,
    coverImage: '/assets/images/tech_biotech_07.jpg',
    views: 3980,
    stars: 164,
    createdAt: '2025-06-05',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-20',
    code: 'CH-PROJ-CUBESAT-2025',
    title: 'Low-Earth Orbit CubeSat Attitude Control',
    tagline: 'Sub-arcsecond 3-axis reaction wheel & star tracker module for 3U sats.',
    description: 'Miniaturized brushless reaction wheels dynamic balancing rig with FPGA-driven star tracker centroid algorithms.',
    problemStatement: 'Commercial ADCS packages consume more than 50% of university CubeSat project budgets.',
    objective: 'Provide open COTS bill of materials and flight software under ₹3.5 Lakhs.',
    category: 'SpaceTech',
    stage: 'Open',
    progress: 62,
    owner: {
      name: 'Rohan Deshpande',
      avatar: '/assets/images/tech_space_06.jpg',
      role: 'Avionics Lead',
      organization: 'Team Anant CubeSat'
    },
    location: 'Pilani, Rajasthan',
    timeline: '4 months remaining',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Open Source',
    isPhysical: true,
    requiredSkills: ['SpaceTech', 'ADCS', 'Control Theory', 'C++', 'FPGA'],
    currentContributors: 14,
    maxContributors: 20,
    openTasksCount: 7,
    verified: true,
    coverImage: '/assets/images/tech_space_05.jpg',
    views: 5120,
    stars: 232,
    createdAt: '2025-05-02',
    tasks: [],
    contributors: [],
    files: []
  }
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Hardware Intern',
    organization: 'NovaTech Labs',
    orgLogo: '⚡',
    orgType: 'Startup',
    category: 'Paid Internship',
    location: 'Bengaluru, India',
    isRemote: false,
    duration: '3 months',
    difficulty: 'Intermediate',
    rewardTier: 'Tier 3',
    rewardDetails: '₹25,000/mo + Hardware Kit & Lab Access',
    skillsRequired: ['PCB Design', 'KiCAD', 'Soldering', 'Microcontrollers'],
    description: 'Join our avionics and telemetry hardware engineering team prototyping high-reliability power management boards.',
    verificationRequired: 2,
    deadline: '2026-10-15',
    applicantsCount: 34,
    postedDate: '1 day ago'
  },
  {
    id: 'opp-2',
    title: 'Research Assistant',
    organization: 'IIT Research Lab',
    orgLogo: '🔬',
    orgType: 'Research Lab',
    category: 'Research Assistant',
    location: 'Delhi, India',
    isRemote: false,
    duration: '6 months',
    difficulty: 'Advanced',
    rewardTier: 'Tier 4',
    rewardDetails: 'Academic Co-Authorship & Institute Stipend',
    skillsRequired: ['Robotics', 'ROS2', 'Python', 'Kinematics'],
    description: 'Work alongside doctoral candidates on autonomous planetary exploration algorithms and field-testing trials.',
    verificationRequired: 2,
    deadline: '2026-10-20',
    applicantsCount: 48,
    postedDate: '2 days ago'
  },
  {
    id: 'opp-3',
    title: 'PCB Design Contributor',
    organization: 'Open Source Hardware Club',
    orgLogo: '🛠️',
    orgType: 'Open Source',
    category: 'Volunteer',
    location: 'Remote',
    isRemote: true,
    duration: 'Flexible',
    difficulty: 'Beginner',
    rewardTier: 'Tier 2',
    rewardDetails: 'Verified Portfolio Credit & Open Source Badge',
    skillsRequired: ['KiCAD', 'Circuit Design', 'Documentation'],
    description: 'Review and optimize open-source sensor breakout board layouts for community educational kits.',
    verificationRequired: 1,
    deadline: '2026-11-01',
    applicantsCount: 19,
    postedDate: '3 days ago'
  },
  {
    id: 'opp-4',
    title: 'Manufacturing Support',
    organization: 'SkyTech Industries',
    orgLogo: '🏭',
    orgType: 'Business',
    category: 'Project Contribution',
    location: 'Pune, India',
    isRemote: false,
    duration: '2 months',
    difficulty: 'Intermediate',
    rewardTier: 'Tier 3',
    rewardDetails: 'Paid Project Stipend + Industrial CNC Certification',
    skillsRequired: ['CNC Machining', 'CAD/CAM', '3D Printing', 'Quality Assurance'],
    description: 'Assisting small-batch assembly and mechanical tolerance checks for industrial drone chassis production.',
    verificationRequired: 2,
    deadline: '2026-10-30',
    applicantsCount: 22,
    postedDate: '4 days ago'
  }
];

export const MOCK_LEARNING_MODULES: CourseModule[] = [
  {
    id: 'learn-1',
    title: 'AI for Real-World Projects',
    description: 'Practical computer vision, edge inferencing, and multimodal intelligence applied to physical robotics and sensor networks.',
    category: 'AI & ML',
    level: 'Beginner',
    duration: '4 Hours',
    modulesCount: 6,
    enrolledCount: 14200,
    rating: 4.8,
    progress: 75,
    thumbnail: '/assets/images/card_aiml_developer.jpg',
    skillsTaught: ['Computer Vision', 'PyTorch', 'Edge AI', 'Model Deployment'],
    linkedProjectsCount: 24
  },
  {
    id: 'learn-2',
    title: 'PCB Design and Prototyping',
    description: 'From schematic capture to Gerber generation. Master multi-layer PCB design, impedance matching, and DFM using KiCAD 8.',
    category: 'Electronics',
    level: 'Intermediate',
    duration: '6 Hours',
    modulesCount: 8,
    enrolledCount: 9800,
    rating: 4.7,
    progress: 40,
    thumbnail: '/assets/images/card_pcb_design.jpg',
    skillsTaught: ['KiCAD', 'Routing', 'Design Rules', 'SMT Soldering'],
    linkedProjectsCount: 18
  },
  {
    id: 'learn-3',
    title: 'Robotics and Embedded Systems',
    description: 'Build complete robotic systems from motor control and sensor fusion to ROS2 communication nodes and trajectory planning.',
    category: 'Robotics',
    level: 'Intermediate',
    duration: '8 Hours',
    modulesCount: 10,
    enrolledCount: 12500,
    rating: 4.9,
    progress: 20,
    thumbnail: '/assets/images/card_robotics_intern.jpg',
    skillsTaught: ['ROS2', 'C++', 'Microcontrollers', 'Kinematics', 'Actuators'],
    linkedProjectsCount: 32
  },
  {
    id: 'learn-4',
    title: '3D Modeling & Printing',
    description: 'Design functional mechanical enclosures and structural parts using parametric CAD and slice for industrial additive manufacturing.',
    category: 'Design & CAD',
    level: 'Beginner',
    duration: '4 Hours',
    modulesCount: 5,
    enrolledCount: 8100,
    rating: 4.6,
    progress: 0,
    thumbnail: '/assets/images/card_3d_printing.jpg',
    skillsTaught: ['SolidWorks', 'Fusion 360', 'FDM Slicing', 'Tolerancing'],
    linkedProjectsCount: 15
  },
  {
    id: 'learn-5',
    title: 'Quantum Computing Fundamentals',
    description: 'Understand quantum gates, transmon qubits, pulse generation with Qiskit, and cryogenic circuit interfaces.',
    category: 'Research',
    level: 'Advanced',
    duration: '10 Hours',
    modulesCount: 12,
    enrolledCount: 4300,
    rating: 4.9,
    progress: 10,
    thumbnail: '/assets/images/card_quantum_computing.jpg',
    skillsTaught: ['Qiskit', 'Cryogenic Circuits', 'Quantum Gates', 'RF Control'],
    linkedProjectsCount: 12
  },
  {
    id: 'learn-6',
    title: 'Clean Energy Systems & Battery Tech',
    description: 'Design battery management systems (BMS), analyze solid-state electrolytes, and simulate micro-grid solar-wind hybrid sync.',
    category: 'CleanTech',
    level: 'Intermediate',
    duration: '7 Hours',
    modulesCount: 9,
    enrolledCount: 6200,
    rating: 4.8,
    progress: 0,
    thumbnail: '/assets/images/card_wind_solar_hybrid.jpg',
    skillsTaught: ['BMS', 'Solar PV', 'Solid State', 'Inverters'],
    linkedProjectsCount: 16
  },
  {
    id: 'learn-7',
    title: 'CRISPR & Synthetic Bio-Engineering',
    description: 'Principles of guide RNA synthesis, automated microfluidic biochip operation, and fluorescent assay verification.',
    category: 'Healthcare',
    level: 'Advanced',
    duration: '8 Hours',
    modulesCount: 8,
    enrolledCount: 3500,
    rating: 4.9,
    progress: 0,
    thumbnail: '/assets/images/card_biotech_crispr.jpg',
    skillsTaught: ['CRISPR Cas13', 'Microfluidics', 'Genomic Splicing', 'Assays'],
    linkedProjectsCount: 10
  },
  {
    id: 'learn-8',
    title: 'CubeSat Avionics & Space Systems',
    description: 'Develop radiation-tolerant flight computers, reaction wheel attitude control, and optical inter-satellite downlinks.',
    category: 'Hardware',
    level: 'Advanced',
    duration: '9 Hours',
    modulesCount: 11,
    enrolledCount: 5100,
    rating: 4.9,
    progress: 0,
    thumbnail: '/assets/images/card_satellite_project.jpg',
    skillsTaught: ['Orbital Dynamics', 'Radiation Hardening', 'Optical Comms', 'CubeSat CAD'],
    linkedProjectsCount: 14
  },
  {
    id: 'learn-9',
    title: 'Advanced Nanomaterial Synthesis & Characterization',
    description: 'Learn chemical vapor deposition, SEM imaging, and carbon nanotube integration on flexible substrates.',
    category: 'Research',
    level: 'Advanced',
    duration: '8 Hours',
    modulesCount: 9,
    enrolledCount: 3800,
    rating: 4.8,
    progress: 0,
    thumbnail: '/assets/images/tech_education_08.jpg',
    skillsTaught: ['CVD', 'Nanotubes', 'Electron Microscopy', 'Materials'],
    linkedProjectsCount: 11
  },
  {
    id: 'learn-10',
    title: 'Smart Industrial Robotics & PLC Integration',
    description: 'Master IEC 61131-3 industrial programming, safety interlocks, and EtherCAT communication for collaborative robotic workcells.',
    category: 'Robotics',
    level: 'Intermediate',
    duration: '7 Hours',
    modulesCount: 8,
    enrolledCount: 5400,
    rating: 4.9,
    progress: 0,
    thumbnail: '/assets/images/tech_education_09.jpg',
    skillsTaught: ['PLC', 'EtherCAT', 'Industrial Arms', 'Workcell Safety'],
    linkedProjectsCount: 19
  },
  {
    id: 'learn-11',
    title: 'Cleanroom Semiconductor Metrology & Yield',
    description: 'Hands-on protocols for ellipsometry, profilometry, spectroscopic wafer inspection, and defect reduction in sub-micron fabrication.',
    category: 'Electronics',
    level: 'Advanced',
    duration: '6 Hours',
    modulesCount: 7,
    enrolledCount: 2900,
    rating: 4.7,
    progress: 0,
    thumbnail: '/assets/images/tech_education_10.jpg',
    skillsTaught: ['Ellipsometry', 'Metrology', 'Wafer Fab', 'Defect Analysis'],
    linkedProjectsCount: 8
  },
  {
    id: 'learn-12',
    title: 'Hardware Venture Incubation & Grant Strategy',
    description: 'Formulate hardware bills of materials, navigate manufacturing supply chains, pitch deep-tech VCs, and secure national research grants.',
    category: 'Business',
    level: 'Beginner',
    duration: '5 Hours',
    modulesCount: 6,
    enrolledCount: 7600,
    rating: 4.8,
    progress: 0,
    thumbnail: '/assets/images/tech_startup_08.jpg',
    skillsTaught: ['BOM Optimization', 'Pitch Decks', 'Supply Chain', 'Gov Grants'],
    linkedProjectsCount: 22
  }
];

export const MOCK_LEARNING_PATHS = [
  {
    id: 'path-1',
    title: 'Become a Robotics Developer',
    description: 'Master mechanical design, embedded firmware, sensor fusion, and ROS2 navigation.',
    coursesCount: 6,
    projectsCount: 3,
    enrolledCount: 4200,
    thumbnail: '/assets/images/card_robotics_intern.jpg'
  },
  {
    id: 'path-2',
    title: 'AI for Innovators',
    description: 'From foundational deep learning models to on-device edge AI and computer vision.',
    coursesCount: 5,
    projectsCount: 2,
    enrolledCount: 6800,
    thumbnail: '/assets/images/card_aiml_developer.jpg'
  },
  {
    id: 'path-3',
    title: 'Hardware Product Design',
    description: 'Take ideas from napkin sketches to functional prototypes, KiCAD boards, and manufacturing.',
    coursesCount: 7,
    projectsCount: 3,
    enrolledCount: 3900,
    thumbnail: '/assets/images/card_pcb_design.jpg'
  },
  {
    id: 'path-4',
    title: 'Research & Publication',
    description: 'Formulate hypotheses, design reproducible lab experiments, and publish peer-reviewed papers.',
    coursesCount: 4,
    projectsCount: 1,
    enrolledCount: 2400,
    thumbnail: '/assets/images/card_nanomaterials_research.jpg'
  },
  {
    id: 'path-5',
    title: 'Build a Startup',
    description: 'Validate deep-tech ideas, build minimum viable prototypes, find co-founders, and pitch angels.',
    coursesCount: 5,
    projectsCount: 2,
    enrolledCount: 5100,
    thumbnail: '/assets/images/card_autonomous_ev.jpg'
  }
];

export const MOCK_FACILITIES: InfrastructureFacility[] = [
  {
    id: 'fac-1',
    name: 'Advanced AI & Robotics Lab',
    type: 'Robotics',
    institution: 'IIT Delhi Innovation Park',
    location: 'Hauz Khas, New Delhi',
    coordinates: { x: 38, y: 28 },
    distance: '5 km away',
    equipment: ['UR5e Collaborative Cobots', 'Stereo Vision Rigs', 'Motion Capture Arena', 'NVIDIA DGX Cluster'],
    capacity: '24 workstations (70% in use)',
    availability: 'Immediate',
    supportedWork: ['Robotics Navigation', 'Computer Vision', 'Deep Learning Inference', 'SLAM Testing'],
    provider: 'IIT Delhi Nanoscale Research Facility',
    hourlyRate: 'Subsidized for verified students (₹150/hr)',
    status: 'Available',
    image: '/assets/images/tech_robotics_01.jpg'
  },
  {
    id: 'fac-2',
    name: 'TinkerHub Makerspace',
    type: '3D Printing',
    institution: 'NIT Trichy Innovation Zone',
    location: 'Tiruchirappalli, Tamil Nadu',
    coordinates: { x: 48, y: 84 },
    distance: '2 km away',
    equipment: ['Industrial FDM 3D Printers', 'Epilog Laser Cutters 120W', 'Desktop CNC Routers', 'Soldering Stations'],
    capacity: '35 open desks',
    availability: 'Immediate',
    supportedWork: ['Rapid Prototyping', 'Chassis Fabrication', 'Laser Cutting', 'Physical Computing'],
    provider: 'NIT Trichy Center for Innovation',
    hourlyRate: 'Free for open-source projects',
    status: 'Available',
    image: '/assets/images/card_3d_printing.jpg'
  },
  {
    id: 'fac-3',
    name: 'Clean Energy Research Center',
    type: 'Testing & Calibration',
    institution: 'IISc Bengaluru',
    location: 'Malleshwaram, Bengaluru',
    coordinates: { x: 42, y: 72 },
    distance: '8 km away',
    equipment: ['Solar Simulator Class AAA', 'Battery Cycler 64-Channel', 'Environmental Test Chamber (-40°C to 150°C)', 'Impedance Spectrometer'],
    capacity: '12 dedicated test cells',
    availability: 'Waitlist (2 days)',
    supportedWork: ['Renewable Energy', 'Battery Management', 'Solar Testing', 'Extreme Weather Validation'],
    provider: 'IISc Center for Sustainable Tech',
    hourlyRate: '₹200/hr for student teams',
    status: 'Reserved',
    image: '/assets/images/card_wind_solar_hybrid.jpg'
  },
  {
    id: 'fac-4',
    name: 'Electronics Prototyping Lab',
    type: 'Electronics & PCB',
    institution: 'IIIT Hyderabad',
    location: 'Gachibowli, Hyderabad',
    coordinates: { x: 44, y: 58 },
    distance: '15 km away',
    equipment: ['Pick & Place SMT Machine', '1GHz 4-Channel Oscilloscopes', 'Reflow Oven (8 Zones)', 'Spectrum Analyzer to 6GHz'],
    capacity: '20 high-speed electronic benches',
    availability: 'Immediate',
    supportedWork: ['PCB Fabrication', 'Surface Mount Assembly', 'RF Characterization', 'Firmware Flashing'],
    provider: 'IIIT Smart City Living Lab',
    hourlyRate: '₹120/hr',
    status: 'Available',
    image: '/assets/images/card_pcb_design.jpg'
  }
];

export const MOCK_POPULAR_EQUIPMENT = [
  {
    id: 'eq-1',
    name: '3D Printer',
    model: 'Prusa i3 MK4',
    category: 'Additive Manufacturing',
    image: '/assets/images/card_3d_printing.jpg',
    availableUnits: 14,
    locationsCount: 8
  },
  {
    id: 'eq-2',
    name: 'Laser Cutter',
    model: 'Glowforge Pro',
    category: 'Rapid Subtractive',
    image: '/assets/images/tech_manufacturing_04.jpg',
    availableUnits: 9,
    locationsCount: 5
  },
  {
    id: 'eq-3',
    name: 'Robotic Arm',
    model: 'Universal Robots UR5e',
    category: 'Industrial Automation',
    image: '/assets/images/card_robotics_intern.jpg',
    availableUnits: 6,
    locationsCount: 3
  },
  {
    id: 'eq-4',
    name: 'CNC Milling Machine',
    model: 'Tormach 1100M',
    category: 'Subtractive Precision',
    image: '/assets/images/card_manufacturing_intern.jpg',
    availableUnits: 4,
    locationsCount: 4
  }
];

export const MOCK_FEED_POSTS: FeedPost[] = [
  {
    id: 'post-1',
    author: {
      name: 'Zaman',
      avatar: '/assets/images/tech_robotics_01.jpg',
      handle: '@zaman',
      role: 'Project Lead • Autonomous Rover',
      verificationLevel: 2
    },
    project: {
      id: 'proj-01',
      title: 'Autonomous Rover',
      code: 'CH-PROJ-ROVER-2025',
      progress: 72
    },
    type: 'PROJECT UPDATE',
    title: 'Autonomous Rover - Field Testing Complete! 🚀',
    content: 'Just concluded a full day of terrain navigation trials in the Delhi ridge quarry sandpit. Our stereoscopic SLAM node handled severe 35-degree gravel gradients without wheel slippage or motor stall. Huge thanks to Priya Sharma and Arjun Mehta for refining the CAN-bus motor timing!',
    mediaUrl: '/assets/images/card_robotics_intern.jpg',
    skillsUsed: ['Robotics', 'Embedded', 'FieldTesting', 'Innovation'],
    task: 'Stereoscopic Depth Map SLAM Tuning',
    contributionStatus: 'Verified',
    likes: 184,
    comments: 29,
    shares: 42,
    collaboratorsInterested: 12,
    timestamp: '2h ago in #Robotics',
    isLiked: true
  },
  {
    id: 'post-2',
    author: {
      name: 'Priya Sharma',
      avatar: '/assets/images/tech_biotech_01.jpg',
      handle: '@priyasharma',
      role: 'Hardware Engineer at AgriMesh',
      verificationLevel: 3
    },
    type: 'RESEARCH PAPER',
    title: 'New Research on Flexible Electronics & Wearable Bio-Sensors',
    content: 'We synthesized ultra-thin polyimide substrates supporting silver-nanoparticle traces that endure over 10,000 bend cycles with zero impedance loss. Ideal for smart epidermal wearables and agricultural leaf sensors.',
    mediaUrl: '/assets/images/card_wearable_biosensor.jpg',
    skillsUsed: ['Research', 'FlexibleElectronics', 'Healthcare', 'IoT'],
    contributionStatus: 'Verified',
    likes: 215,
    comments: 18,
    shares: 37,
    collaboratorsInterested: 9,
    timestamp: '5h ago in #Research',
    isLiked: false
  },
  {
    id: 'post-3',
    author: {
      name: 'Aarav Singh',
      avatar: '/assets/images/tech_robotics_02.jpg',
      handle: '@aarav_mech',
      role: 'Mechatronics Engineer',
      verificationLevel: 3
    },
    project: {
      id: 'proj-04',
      title: 'Bionic Hand Prototype',
      code: 'CH-PROJ-BIONIC-2025',
      progress: 60
    },
    type: 'TECHNICAL WORK',
    title: '3D Printed Robotic Arm v2.0 Assembly & Testing',
    content: 'Upgraded our 6-DOF robotic manipulator with harmonic-drive cycloidal gears and integrated magnetic rotary encoders. Repeatability is now under 0.2mm. STEP files and firmware are available in our open workspace!',
    mediaUrl: '/assets/images/card_3d_printing.jpg',
    skillsUsed: ['3DPrinting', 'Robotics', 'OpenSource', 'Hardware'],
    task: 'Arm Joint Kinematics Calibration',
    contributionStatus: 'Verified',
    likes: 310,
    comments: 42,
    shares: 65,
    collaboratorsInterested: 18,
    timestamp: '1d ago in #Hardware',
    isLiked: false
  },
  {
    id: 'post-4',
    author: {
      name: 'Rohit Mehta',
      avatar: '/assets/images/tech_circuit_01.jpg',
      handle: '@rohit_pcb',
      role: 'Hardware Designer',
      verificationLevel: 2
    },
    type: 'PROJECT UPDATE',
    title: 'Best PCB Manufacturer in India for 4-Layer Controlled Impedance?',
    content: 'We are manufacturing high-speed USB 3.0 and differential RF tracks for our open satellite receiver. Looking for fabricators offering quick turnarounds under 5 days in Bengaluru or Pune with ENIG finish.',
    mediaUrl: '/assets/images/card_pcb_design.jpg',
    skillsUsed: ['PCB', 'Manufacturing', 'Hardware', 'KiCAD'],
    likes: 95,
    comments: 34,
    shares: 11,
    collaboratorsInterested: 4,
    timestamp: '1d ago in #PCB',
    isLiked: false
  },
  {
    id: 'post-5',
    author: {
      name: 'Sneha Iyer',
      avatar: '/assets/images/tech_education_01.jpg',
      handle: '@sneha_stem',
      role: 'STEM Educator & Community Lead',
      verificationLevel: 3
    },
    type: 'TECHNICAL WORK',
    title: 'Volunteers Needed for Rural STEM Workshop in Himachal',
    content: 'CraftHub members are traveling to Shimla next month to distribute 50 open-hardware microcontroller learning kits to high-school students. If you want to mentor hands-on workshops, drop a comment below!',
    mediaUrl: '/assets/images/card_aiml_developer.jpg',
    skillsUsed: ['Education', 'STEM', 'Community', 'Mentorship'],
    likes: 188,
    comments: 27,
    shares: 39,
    collaboratorsInterested: 15,
    timestamp: '2d ago in #Community',
    isLiked: true
  },
  {
    id: 'post-6',
    author: {
      name: 'Dr. Alok Sen',
      avatar: '/assets/images/tech_education_03.jpg',
      handle: '@alok_space',
      role: 'Photonics Lead • ISRO Node',
      verificationLevel: 3
    },
    type: 'RESEARCH PAPER',
    title: 'Optical Laser Downlink Over 800km Free Space Tested',
    content: 'We established an eye-safe 1550nm coherent laser optical link between mountain peaks with sub-microradian pointing stability. Data throughput reached 1.25 Gbps with error correction.',
    mediaUrl: '/assets/images/tech_space_10.jpg',
    skillsUsed: ['Photonics', 'Optics', 'SpaceTech', 'LaserComms'],
    contributionStatus: 'Verified',
    likes: 240,
    comments: 31,
    shares: 48,
    collaboratorsInterested: 19,
    timestamp: '2d ago in #SpaceTech',
    isLiked: false
  },
  {
    id: 'post-7',
    author: {
      name: 'Vikram Patel',
      avatar: '/assets/images/tech_education_04.jpg',
      handle: '@vikram_hw',
      role: 'Hardware Architect',
      verificationLevel: 3
    },
    type: 'PROJECT UPDATE',
    title: 'Open-Source 4-Layer Controlled Impedance Stackup Verified',
    content: 'Completed TDR testing on our high-speed DDR3 memory breakout board. Differential impedance held strictly within 90 ohms ± 4% across the entire PCB panel.',
    mediaUrl: '/assets/images/tech_lab_04.jpg',
    skillsUsed: ['PCB', 'Hardware', 'SignalIntegrity', 'KiCAD'],
    contributionStatus: 'Verified',
    likes: 195,
    comments: 22,
    shares: 34,
    collaboratorsInterested: 8,
    timestamp: '3d ago in #Hardware',
    isLiked: false
  },
  {
    id: 'post-8',
    author: {
      name: 'Dr. Malini Roy',
      avatar: '/assets/images/tech_education_05.jpg',
      handle: '@malini_bio',
      role: 'Biomaterials Scientist',
      verificationLevel: 3
    },
    type: 'TECHNICAL WORK',
    title: 'Microfluidic Droplet Generator Operating at 12 kHz',
    content: 'Fabricated PDMS flow-focusing channels using soft lithography. Generating 45-micron monodisperse alginate droplets for cellular encapsulation with zero clogging.',
    mediaUrl: '/assets/images/tech_lab_09.jpg',
    skillsUsed: ['Microfluidics', 'BioTech', 'Lithography', 'Materials'],
    contributionStatus: 'Verified',
    likes: 172,
    comments: 19,
    shares: 26,
    collaboratorsInterested: 11,
    timestamp: '3d ago in #BioTech',
    isLiked: false
  },
  {
    id: 'post-9',
    author: {
      name: 'Rohan Deshpande',
      avatar: '/assets/images/tech_education_06.jpg',
      handle: '@rohan_sat',
      role: 'CubeSat Avionics Lead',
      verificationLevel: 2
    },
    type: 'PROJECT UPDATE',
    title: 'CubeSat Attitude Determination Test on Air Bearing Table',
    content: 'Tested our magnetic torquer coils and reaction wheels on a spherical frictionless air-bearing platform. Detumbling from 15 deg/s took under 4 minutes with B-dot control.',
    mediaUrl: '/assets/images/tech_startup_06.jpg',
    skillsUsed: ['SpaceTech', 'ADCS', 'CubeSat', 'ControlTheory'],
    contributionStatus: 'Verified',
    likes: 285,
    comments: 44,
    shares: 61,
    collaboratorsInterested: 23,
    timestamp: '4d ago in #SpaceTech',
    isLiked: true
  },
  {
    id: 'post-10',
    author: {
      name: 'Kavita Menon',
      avatar: '/assets/images/tech_education_07.jpg',
      handle: '@kavita_ev',
      role: 'EV Powertrain Engineer',
      verificationLevel: 3
    },
    type: 'TECHNICAL WORK',
    title: 'Modular EV Skateboard Chassis Dynamometer Results',
    content: 'Full-load thermal dynamometer testing of our liquid-cooled dual-inverter setup showed 94.2% peak efficiency and sub-60°C IGBT junction temperatures under 150kW bursts.',
    mediaUrl: '/assets/images/tech_startup_07.jpg',
    skillsUsed: ['EVMobility', 'PowerElectronics', 'ThermalManagement', 'Inverters'],
    contributionStatus: 'Verified',
    likes: 312,
    comments: 53,
    shares: 72,
    collaboratorsInterested: 29,
    timestamp: '5d ago in #CleanTech',
    isLiked: false
  },
  {
    id: 'post-11',
    author: {
      name: 'Arjun Nair',
      avatar: '/assets/images/tech_startup_04.jpg',
      handle: '@arjun_swarm',
      role: 'Flight Systems Specialist',
      verificationLevel: 3
    },
    type: 'PROJECT UPDATE',
    title: 'Autonomous Swarm Outdoor Mesh Test Across 10 Drones',
    content: 'Validated decentralized consensus algorithms over 2.4GHz WiFi broadcast in windy conditions. The swarm formed dynamic defensive perimeters around ground targets seamlessly.',
    mediaUrl: '/assets/images/tech_space_08.jpg',
    skillsUsed: ['Drones', 'SwarmRobotics', 'PX4', 'ROS2'],
    contributionStatus: 'Verified',
    likes: 420,
    comments: 68,
    shares: 95,
    collaboratorsInterested: 36,
    timestamp: '6d ago in #Robotics',
    isLiked: true
  }
];

export const MOCK_STARTUPS: StartupEntity[] = [
  {
    id: 'st-1',
    name: 'AgriSense',
    tagline: 'Precision AI-powered soil and crop monitoring drone network.',
    founder: 'Siddharth Rao',
    stage: 'Early Stage',
    category: 'AgriTech / Sustainability',
    teamSize: 8,
    problem: 'Farmers lose up to 40% of seasonal yield to undetected fungal leaf blights.',
    solution: 'Autonomous multi-spectral drones and IoT soil sensors providing actionable plant health maps.',
    openRoles: 3,
    infrastructureNeeded: ['Testing Farm (5 acres)', 'Electronics Assembly Cleanroom', 'RF Test Bed'],
    fundingStatus: 'Seed Stage (₹1.8 Cr Raised)',
    logo: '🌱',
    location: 'Punjab / Bengaluru',
    coverImage: '/assets/images/card_smart_agriculture.jpg'
  },
  {
    id: 'st-2',
    name: 'MediMind',
    tagline: 'Predictive health insights and non-invasive biometric monitoring smartwatch.',
    founder: 'Dr. Ananya Rao',
    stage: 'Prototype',
    category: 'HealthTech / AI',
    teamSize: 6,
    problem: 'Cardiovascular arrhythmia spikes occur silently outside clinical diagnostic visits.',
    solution: 'Continuous photoplethysmography and edge ECG neural models warning patients 30 minutes in advance.',
    openRoles: 2,
    infrastructureNeeded: ['Biocompatible 3D Printing', 'Clinical Calibration Testbed'],
    fundingStatus: 'Pre-Seed (₹60 Lakh)',
    logo: '🩺',
    location: 'Hyderabad',
    coverImage: '/assets/images/card_wearable_biosensor.jpg'
  },
  {
    id: 'st-3',
    name: 'ReCircle',
    tagline: 'Smart reverse vending and municipal automated recycling bins.',
    founder: 'Rohan Mehta',
    stage: 'Growth',
    category: 'CleanTech / IoT',
    teamSize: 12,
    problem: '90% of discarded plastic bottles never enter municipal recycling loops due to lack of incentive.',
    solution: 'AI smart bin identifying plastic polymer types and instantly crediting digital UPI rewards to citizens.',
    openRoles: 4,
    infrastructureNeeded: ['Sheet Metal Fabrication', 'CNC Milling'],
    fundingStatus: 'Series A (₹5.2 Cr Raised)',
    logo: '♻️',
    location: 'Mumbai / Pune',
    coverImage: '/assets/images/card_sustainability_project.jpg'
  },
  {
    id: 'st-4',
    name: 'LearnLoop',
    tagline: 'Adaptive AI skill development platform for engineering students.',
    founder: 'Karan Verma',
    stage: 'Early Stage',
    category: 'EdTech / AI',
    teamSize: 5,
    problem: 'Engineering graduates face an 80% employable skills mismatch with hardware industries.',
    solution: 'Project-first interactive curriculum paired with open hardware kit simulations.',
    openRoles: 2,
    infrastructureNeeded: ['Cloud Compute', 'High-Performance Hosting'],
    fundingStatus: 'Seed Stage (₹1.2 Cr)',
    logo: '🎓',
    location: 'Bengaluru',
    coverImage: '/assets/images/card_aiml_developer.jpg'
  },
  {
    id: 'st-5',
    name: 'RoboKart',
    tagline: 'Autonomous last-mile delivery robot for universities and hospitals.',
    founder: 'Rakesh Verma',
    stage: 'Prototype',
    category: 'Robotics / Logistics',
    teamSize: 7,
    problem: 'Intra-campus medicine and logistics movement requires manual courier delivery.',
    solution: '4-wheel drive lidar-equipped autonomous delivery rover with tamper-proof digital compartments.',
    openRoles: 3,
    infrastructureNeeded: ['Robotics Test Track', 'SMT PCB Assembly'],
    fundingStatus: 'Bootstrapped / Grant (₹40 Lakh)',
    logo: '🤖',
    location: 'Delhi',
    coverImage: '/assets/images/card_robotics_intern.jpg'
  },
  {
    id: 'st-6',
    name: 'AeroSky Drone Tech',
    tagline: 'High-altitude autonomous disaster surveillance and medical drop VTOLs.',
    founder: 'Vikram Sethi',
    stage: 'Early Stage',
    category: 'Aerospace / Hardware',
    teamSize: 9,
    problem: 'Landslides sever road transit during monsoon seasons in Himalayan valleys.',
    solution: 'Long-range hybrid VTOL autonomous drones carrying 4kg life-saving payloads across 50km.',
    openRoles: 4,
    infrastructureNeeded: ['Wind Tunnel Testing', 'Carbon Fiber Curing Oven'],
    fundingStatus: 'Seed Stage (₹2.4 Cr)',
    logo: '🚁',
    location: 'Uttarakhand / Delhi',
    coverImage: '/assets/images/card_drone_swarm.jpg'
  },
  {
    id: 'st-7',
    name: 'VoltGen Energy',
    tagline: 'Solid-state electrolyte micro-batteries for extreme-temperature commercial IoT.',
    founder: 'Kavita Chawla',
    stage: 'Growth',
    category: 'CleanTech / Energy',
    teamSize: 11,
    problem: 'Lithium battery performance drops 60% below 0°C in high-altitude sensor networks.',
    solution: 'Non-flammable garnet solid-state cell architecture stable from -40°C to +80°C.',
    openRoles: 3,
    infrastructureNeeded: ['Glovebox Dryroom', 'Impedance Spectrometer'],
    fundingStatus: 'Series A (₹6.8 Cr)',
    logo: '⚡',
    location: 'Chennai / Bengaluru',
    coverImage: '/assets/images/card_wind_solar_hybrid.jpg'
  },
  {
    id: 'st-8',
    name: 'QuantumCore Systems',
    tagline: 'Cryogenic quantum control processors and QKD photonic encryption modules.',
    founder: 'Dr. Srinivas Rao',
    stage: 'Early Stage',
    category: 'Deep Tech / Quantum',
    teamSize: 6,
    problem: 'Current telecom encryption is vulnerable to upcoming quantum factoring algorithms.',
    solution: 'Hardware QKD optical transceivers providing unhackable quantum key distribution.',
    openRoles: 2,
    infrastructureNeeded: ['Cryogenic Dilution Fridge', 'Single Photon Detectors'],
    fundingStatus: 'Seed Stage (₹3.5 Cr)',
    logo: '🔮',
    location: 'Bengaluru',
    coverImage: '/assets/images/card_quantum_computing.jpg'
  },
  {
    id: 'st-9',
    name: 'OrbitalDynamics',
    tagline: 'Precision attitude determination and star tracker avionics for commercial smallsats.',
    founder: 'Rohan Deshpande',
    stage: 'Early Stage',
    category: 'Deep Tech / SpaceTech',
    teamSize: 8,
    problem: 'Commercial satellite ADCS hardware is expensive and closed-source.',
    solution: 'Modular open-spec reaction wheels and sub-arcsecond CMOS star trackers.',
    openRoles: 4,
    infrastructureNeeded: ['Thermal Vacuum Chamber', 'Air Bearing Table'],
    fundingStatus: 'Seed Stage (₹4.2 Cr)',
    logo: '🛰️',
    location: 'Bengaluru / Pune',
    coverImage: '/assets/images/tech_space_07.jpg'
  },
  {
    id: 'st-10',
    name: 'NeuroSilicon Systems',
    tagline: 'Event-driven neuromorphic silicon architectures for low-latency robotics.',
    founder: 'Prof. Srinivas Rao',
    stage: 'Growth',
    category: 'Semiconductor / AI',
    teamSize: 14,
    problem: 'Frame-based camera processing consumes too much power for miniature drones.',
    solution: 'Asynchronous spike-based neural cores processing asynchronous event streams at sub-50mW.',
    openRoles: 5,
    infrastructureNeeded: ['EDA Tool Cluster', 'Cryo Probe Station'],
    fundingStatus: 'Series A (₹12.5 Cr)',
    logo: '🧠',
    location: 'Hyderabad / Chennai',
    coverImage: '/assets/images/tech_circuit_10.jpg'
  },
  {
    id: 'st-11',
    name: 'BioSynthetix Labs',
    tagline: 'Microfluidic cell sorting and point-of-care viral diagnostic cartridges.',
    founder: 'Dr. Priya Sharma',
    stage: 'Early Stage',
    category: 'Biotech / Healthcare',
    teamSize: 9,
    problem: 'Centralized clinical laboratory assays have 48-hour turnarounds.',
    solution: 'Disposable microfluidic chips utilizing CRISPR Cas13 with 15-minute optical readout.',
    openRoles: 3,
    infrastructureNeeded: ['BSL-2 Cleanroom', 'Fluorescence Microscope'],
    fundingStatus: 'Seed Stage (₹5.0 Cr)',
    logo: '🧬',
    location: 'Bengaluru',
    coverImage: '/assets/images/tech_biotech_09.jpg'
  },
  {
    id: 'st-12',
    name: 'AeroForge Dynamics',
    tagline: 'Decentralized autonomous UAV mesh networks for disaster emergency mapping.',
    founder: 'Arjun Nair',
    stage: 'Growth',
    category: 'Robotics / Aerospace',
    teamSize: 16,
    problem: 'Single-drone coverage fails in mountainous and GPS-denied earthquake zones.',
    solution: 'Collaborative swarm autonomy with distributed visual SLAM and ad-hoc radio mesh.',
    openRoles: 6,
    infrastructureNeeded: ['Wind Tunnel', 'Anechoic Chamber'],
    fundingStatus: 'Series A (₹9.8 Cr)',
    logo: '🚁',
    location: 'Pune / Delhi NCR',
    coverImage: '/assets/images/tech_startup_05.jpg'
  }
];

export const MOCK_BUSINESSES: BusinessEntity[] = [
  {
    id: 'biz-1',
    name: 'Tesla India',
    tagline: 'Accelerating the world\'s transition to sustainable energy and electric mobility.',
    category: 'Automotive / Clean Energy',
    location: 'Bengaluru, India',
    type: 'Global Player',
    tags: ['Electric Vehicles', 'Battery Tech', 'Autonomous Driving', 'Renewables'],
    coverImage: '/assets/images/card_autonomous_ev.jpg',
    logo: '⚡',
    description: 'Partnering with academic institutions and hardware startups on EV battery thermal management, charging infrastructure, and power electronics.',
    openProjects: 8,
    openRoles: 14,
    partnershipOpportunities: 5
  },
  {
    id: 'biz-2',
    name: 'L&T Technology Services',
    tagline: 'Engineering the future with intelligent automation, smart factories, and IoT.',
    category: 'Engineering & Automation',
    location: 'Chennai / Mumbai, India',
    type: 'Industry Leader',
    tags: ['Robotics', 'Industrial IoT', 'Digital Twins', 'Embedded Systems'],
    coverImage: '/assets/images/card_manufacturing_intern.jpg',
    logo: '🏗️',
    description: 'Collaborating on deep-tech hardware incubators, offering lab access and prototype testing for industrial robotic arms and telematics.',
    openProjects: 12,
    openRoles: 26,
    partnershipOpportunities: 9
  },
  {
    id: 'biz-3',
    name: 'SELCO Foundation',
    tagline: 'Social innovations using sustainable solar energy for underserved livelihoods.',
    category: 'Renewable Energy / Social Impact',
    location: 'Bengaluru, India',
    type: 'Social Enterprise',
    tags: ['Solar Power', 'Grassroots Innovation', 'Healthcare Tech', 'Agri-Processing'],
    coverImage: '/assets/images/card_wind_solar_hybrid.jpg',
    logo: '☀️',
    description: 'Funding and prototyping decentralized clean energy equipment for rural health centers, micro-enterprises, and agri-cold storage.',
    openProjects: 6,
    openRoles: 8,
    partnershipOpportunities: 7
  },
  {
    id: 'biz-4',
    name: 'Infosys Innovation Network',
    tagline: 'Navigating your next with enterprise digital transformation and AI ecosystem.',
    category: 'IT Services & AI',
    location: 'Bengaluru / Pune, India',
    type: 'Industry Leader',
    tags: ['Enterprise AI', 'Cloud', 'Cybersecurity', 'Open Innovation'],
    coverImage: '/assets/images/tech_ai_04.jpg',
    logo: '🌐',
    description: 'Connecting enterprise clients with promising academic research and deep-tech startup prototypes for enterprise deployment.',
    openProjects: 15,
    openRoles: 32,
    partnershipOpportunities: 12
  },
  {
    id: 'biz-5',
    name: 'Bharat Forge Robotics',
    tagline: 'Advanced precision forgings, mechatronics, and collaborative industrial manipulators.',
    category: 'Manufacturing & Robotics',
    location: 'Pune, India',
    type: 'Industry Leader',
    tags: ['Cobots', 'Smart Factory', 'Precision Machining', 'Automation'],
    coverImage: '/assets/images/tech_manufacturing_04.jpg',
    logo: '⚙️',
    description: 'Hosting academic test cells for 6-axis articulated welding and assembly arms with sub-millimeter repeatable accuracy.',
    openProjects: 9,
    openRoles: 18,
    partnershipOpportunities: 8
  },
  {
    id: 'biz-6',
    name: 'Tata Power Renewables',
    tagline: 'Pioneering utility-scale solar, wind farms, and distributed smart micro-grids.',
    category: 'Renewable Energy',
    location: 'Mumbai / Delhi, India',
    type: 'Industry Leader',
    tags: ['CleanTech', 'Solar Inverters', 'Smart Grids', 'Energy Storage'],
    coverImage: '/assets/images/tech_energy_01.jpg',
    logo: '🔋',
    description: 'Deploying high-capacity grid storage research and testing bifacial photovoltaic efficiency across pan-India climatic zones.',
    openProjects: 11,
    openRoles: 22,
    partnershipOpportunities: 6
  },
  {
    id: 'biz-7',
    name: 'Biocon Biologics',
    tagline: 'Affordable biologics and novel immuno-oncology therapies through biosimilar innovation.',
    category: 'Healthcare & Life Sciences',
    location: 'Bengaluru, India',
    type: 'Global Player',
    tags: ['BioTech', 'CRISPR', 'Biosimilars', 'Fermentation'],
    coverImage: '/assets/images/card_biotech_crispr.jpg',
    logo: '🧬',
    description: 'Sponsoring academic recombinant protein synthesis and microfluidic cellular sorting platforms.',
    openProjects: 7,
    openRoles: 16,
    partnershipOpportunities: 10
  },
  {
    id: 'biz-8',
    name: 'Intel Foundry VLSI',
    tagline: 'Building the next era of silicon micro-architecture and heterogenous chiplet packaging.',
    category: 'Semiconductors',
    location: 'Bengaluru / Hyderabad, India',
    type: 'Global Player',
    tags: ['Silicon', 'VLSI', 'Cleanroom', 'ASIC'],
    coverImage: '/assets/images/card_cleanroom_nanofab.jpg',
    logo: '💻',
    description: 'Providing university research labs with multi-project wafer (MPW) fabrication access and advanced packaging characterization tools.',
    openProjects: 14,
    openRoles: 28,
    partnershipOpportunities: 11
  },
  {
    id: 'biz-9',
    name: 'Tata Advanced Systems',
    tagline: 'Leading strategic aerospace, unmanned aerial vehicles, and defense electronics manufacturing.',
    category: 'Aerospace & Defense',
    location: 'Hyderabad / Bengaluru, India',
    type: 'Industry Leader',
    tags: ['Aerospace', 'UAV', 'Defense Systems', 'Avionics'],
    coverImage: '/assets/images/tech_space_08.jpg',
    logo: '✈️',
    description: 'Partnering with universities for composite airframe stress testing and supersonic flight telemetry validation.',
    openProjects: 16,
    openRoles: 35,
    partnershipOpportunities: 14
  },
  {
    id: 'biz-10',
    name: 'Reliance New Energy',
    tagline: 'Building gigafactories for photovoltaic cells, green hydrogen electrolyzers, and grid storage.',
    category: 'Renewable Energy',
    location: 'Jamnagar / Mumbai, India',
    type: 'Global Player',
    tags: ['Green Hydrogen', 'Electrolyzers', 'Solar PV', 'CleanTech'],
    coverImage: '/assets/images/tech_energy_09.jpg',
    logo: '🌱',
    description: 'Offering funded grant cohorts for electrochemical membrane research and solid-oxide electrolyzer longevity testing.',
    openProjects: 18,
    openRoles: 42,
    partnershipOpportunities: 15
  },
  {
    id: 'biz-11',
    name: 'Adani Aerospace & Defense',
    tagline: 'Precision aerostructures, autonomous combat drone prototypes, and counter-UAS platforms.',
    category: 'Aerospace & Robotics',
    location: 'Hyderabad, India',
    type: 'Corporate Partners',
    tags: ['Autonomous Flight', 'Composites', 'Radar Systems', 'Robotics'],
    coverImage: '/assets/images/tech_space_09.jpg',
    logo: '🛡️',
    description: 'Collaborating on autonomous swarm control algorithms, carbon-fiber fabrication, and airborne synthetic aperture radar.',
    openProjects: 10,
    openRoles: 20,
    partnershipOpportunities: 8
  },
  {
    id: 'biz-12',
    name: 'Astra Microwave Technologies',
    tagline: 'High-frequency microwave super-heterodyne receivers, phased array radars, and satellite payloads.',
    category: 'Electronics & RF',
    location: 'Hyderabad, India',
    type: 'Innovative SMEs',
    tags: ['RF Engineering', 'Phased Array', 'Radar', 'Space Electronics'],
    coverImage: '/assets/images/tech_startup_09.jpg',
    logo: '📡',
    description: 'Providing student engineers with anechoic chamber testing time and vector network analyzer RF calibration benches.',
    openProjects: 8,
    openRoles: 15,
    partnershipOpportunities: 7
  }
];

export const MOCK_RESEARCH_TOPICS = [
  {
    id: 'res-top-1',
    name: 'Artificial Intelligence',
    papersCount: '120K+ papers',
    image: '/assets/images/card_aiml_developer.jpg',
    activeResearchers: '14,200',
    growth: '+28% this year'
  },
  {
    id: 'res-top-2',
    name: 'Climate Change & Clean Energy',
    papersCount: '85K+ papers',
    image: '/assets/images/card_wind_solar_hybrid.jpg',
    activeResearchers: '9,800',
    growth: '+35% this year'
  },
  {
    id: 'res-top-3',
    name: 'Biomedical Engineering',
    papersCount: '72K+ papers',
    image: '/assets/images/card_biotech_crispr.jpg',
    activeResearchers: '8,400',
    growth: '+19% this year'
  },
  {
    id: 'res-top-4',
    name: 'Quantum Computing',
    papersCount: '68K+ papers',
    image: '/assets/images/card_quantum_computing.jpg',
    activeResearchers: '6,100',
    growth: '+42% this year'
  },
  {
    id: 'res-top-5',
    name: 'Space Exploration',
    papersCount: '54K+ papers',
    image: '/assets/images/card_satellite_project.jpg',
    activeResearchers: '5,300',
    growth: '+24% this year'
  },
  {
    id: 'res-top-6',
    name: 'Sustainable Technologies',
    papersCount: '49K+ papers',
    image: '/assets/images/card_sustainability_project.jpg',
    activeResearchers: '7,200',
    growth: '+31% this year'
  }
];

export const MOCK_RESEARCH_PAPERS: ResearchPaper[] = [
  {
    id: 'paper-1',
    title: 'A Unified Framework for Multimodal Learning in Real-World Robotics',
    category: 'AI & ML',
    journal: 'arXiv / IEEE Transactions on Robotics',
    year: 2025,
    authors: ['Dr. Ananya Rao', 'Zaman', 'Priya Sharma', 'K. Murthy'],
    abstract: 'We introduce a unified vision-language-action foundation model optimized for sub-10W edge compute in autonomous rovers navigating dynamic unstructured planetary and terrestrial environments.',
    citations: 142,
    coverImage: '/assets/images/tech_robotics_02.jpg',
    doi: '10.1109/TRO.2025.0189',
    pdfUrl: '#'
  },
  {
    id: 'paper-2',
    title: 'Scalable Solutions for Carbon-Neutral Energy Systems in Arid Micro-Grids',
    category: 'Sustainability',
    journal: 'Nature Energy / IEEE GreenTech',
    year: 2025,
    authors: ['Dr. Meera Iyer', 'Kavita Chawla', 'S. Gupta'],
    abstract: 'Experimental validation of hybrid bifacial photovoltaic and vertical-axis aerodynamic kinetic capture architectures under high thermal ambient degradation.',
    citations: 98,
    coverImage: '/assets/images/tech_energy_03.jpg',
    doi: '10.1038/s41560-025-0142',
    pdfUrl: '#'
  },
  {
    id: 'paper-3',
    title: 'Next-Generation Myoelectric Signal Acquisition with Dry Carbon Electrodes',
    category: 'Healthcare',
    journal: 'Biomedical Microdevices',
    year: 2024,
    authors: ['Dr. R. Bannerjee', 'BioHeal Research Team'],
    abstract: 'Demonstrating 98.4% pattern recognition accuracy for pediatric bionic upper-limb control with 12-hour continuous skin adherence and sweat compensation.',
    citations: 76,
    coverImage: '/assets/images/card_wearable_biosensor.jpg',
    doi: '10.1007/s10544-024-00712',
    pdfUrl: '#'
  },
  {
    id: 'paper-4',
    title: 'Deep Space Optical Downlink Transceivers in Geostationary Orbit',
    category: 'SpaceTech',
    journal: 'AIAA Journal of Spacecraft and Rockets',
    year: 2025,
    authors: ['Dr. Alok Sen', 'Rohan Deshpande', 'M. Varadarajan'],
    abstract: 'Field demonstration of 10 Gbps coherent optical communication downlinks with adaptive wavefront correction under atmospheric turbulence.',
    citations: 114,
    coverImage: '/assets/images/tech_space_10.jpg',
    doi: '10.2514/1.A35890',
    pdfUrl: '#'
  },
  {
    id: 'paper-5',
    title: 'CRISPR Cas13 Lateral Flow Assays for Rapid Pathogen Profiling',
    category: 'Healthcare',
    journal: 'Nature Biomedical Engineering',
    year: 2025,
    authors: ['Dr. Priya Sharma', 'Dr. Malini Roy', 'S. Narayanan'],
    abstract: 'Development of an isothermal amplification coupled Cas13 diagnostic chip achieving attomolar detection limits within 15 minutes of sample lysis.',
    citations: 156,
    coverImage: '/assets/images/tech_biotech_10.jpg',
    doi: '10.1038/s41551-025-01332',
    pdfUrl: '#'
  },
  {
    id: 'paper-6',
    title: 'Continuous Microfluidic Droplet Generation for Bio-Scaffold Fabrication',
    category: 'Nanotech & Materials',
    journal: 'Advanced Functional Materials',
    year: 2025,
    authors: ['Dr. Ramesh Kulkarni', 'Sneha Iyer', 'V. Joshi'],
    abstract: 'Monodisperse alginate hydrogel microsphere generation yielding 99.4% size consistency for 3D printed cellular vascularization scaffolds.',
    citations: 88,
    coverImage: '/assets/images/tech_lab_10.jpg',
    doi: '10.1002/adfm.20250124',
    pdfUrl: '#'
  }
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'project',
    title: 'New Contributor Joined',
    description: 'Karan Singh joined your Autonomous Rover project team as Computer Vision Specialist.',
    timestamp: '15m ago',
    isRead: false
  },
  {
    id: 'notif-2',
    type: 'contribution',
    title: 'Contribution Verified!',
    description: 'Your contribution "Stereoscopic Depth Map SLAM Tuning" has been verified and awarded Tier 4.',
    timestamp: '2h ago',
    isRead: false
  },
  {
    id: 'notif-3',
    type: 'opportunity',
    title: 'New Hardware Opportunity',
    description: 'NovaTech Labs posted a new paid hardware internship matching your skills.',
    timestamp: '1d ago',
    isRead: true
  },
  {
    id: 'notif-4',
    type: 'verification',
    title: 'Trust Level 2 Verified',
    description: 'Your academic affiliation with IIT Delhi has been verified by the institute coordinator.',
    timestamp: '3d ago',
    isRead: true
  }
];
