import { 
  Project, 
  Opportunity, 
  CourseModule, 
  InfrastructureFacility, 
  FeedPost, 
  StartupEntity, 
  BusinessEntity,
  ResearchPaper,
  NotificationItem, 
  UserProfile 
} from './types';

export const INITIAL_USER: UserProfile = {
  id: 'usr-001',
  name: 'Zaman',
  handle: '@zaman',
  role: 'student',
  headline: 'Builder | Learner | Innovator • Robotics & Embedded Systems',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1600&auto=format&fit=crop&q=80',
  bio: 'Passionate about robotics, embedded systems, and building real solutions for planetary and terrestrial exploration. Open to collaborate on robotics, autonomous navigation, and IoT.',
  location: 'Delhi, India',
  verificationLevel: 2,
  organization: 'Indian Institute of Technology Delhi',
  skills: ['Robotics', 'AI / ML', 'ROS', 'Python', 'C++', 'Embedded Systems', 'Computer Vision', 'PCB Design'],
  learningProgress: 68,
  stats: {
    projects: 4,
    contributions: 18,
    skillsCount: 12,
    certificates: 3,
    opportunitiesCount: 5,
  },
  portfolios: {
    personal: true,
    startups: ['HydroSense Labs', 'AgriMesh'],
    businesses: ['RoboKart'],
    research: ['Autonomous Terrain Navigation Grant'],
    facilities: ['IIT Delhi Maker-pass']
  }
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-01',
    code: 'CH-PROJ-ROVER-2025',
    title: 'Autonomous Rover',
    tagline: 'An AI-powered rover for planetary exploration and research.',
    description: 'This project aims to design and develop an autonomous rover capable of navigating challenging terrains for planetary exploration. It integrates AI-based navigation, sensor fusion, and real-time data analysis to support research missions on Mars and the Moon.',
    problemStatement: 'Off-world terrain mapping requires real-time sub-meter navigation resilience without human teleoperation delays.',
    objective: 'Deploy a tested prototype equipped with stereoscopic visual odometry, ROS2 control stack, and 6-wheel rocker-bogie suspension.',
    category: 'Robotics',
    stage: 'Prototype',
    progress: 72,
    owner: {
      name: 'Zaman',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      role: 'Project Lead',
      organization: 'IIT Delhi'
    },
    location: 'Delhi, India',
    timeline: 'Expected Completion Dec 2025',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Robotics', 'AI', 'Embedded Systems', 'Computer Vision', 'Mechanical Engineering'],
    currentContributors: 8,
    maxContributors: 15,
    openTasksCount: 5,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    views: 4850,
    stars: 96,
    createdAt: '2025-03-10',
    tasks: [
      {
        id: 'task-1',
        title: 'Computer Vision: Stereoscopic Depth Map SLAM Tuning',
        description: 'Implement real-time obstacle disparity computation using OpenCV and CUDA acceleration on Jetson Orin Nano.',
        category: 'AI / Vision',
        status: 'In Progress',
        priority: 'Critical',
        rewardTier: 'Tier 4',
        assignee: {
          name: 'Zaman',
          avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80'
        },
        skillsRequired: ['OpenCV', 'CUDA', 'Python', 'ROS2'],
        dueDate: '2026-09-28'
      },
      {
        id: 'task-2',
        title: 'Mechanical: Rocker-Bogie Suspension Stress Testing in Sand Pit',
        description: 'Fabricate carbon fiber reinforced nylon joints and evaluate tilt stability on 35-degree loose gravel inclines.',
        category: 'Mechanical',
        status: 'Open',
        priority: 'High',
        rewardTier: 'Tier 3',
        skillsRequired: ['SolidWorks', '3D Printing', 'Stress Analysis'],
        dueDate: '2026-10-05'
      },
      {
        id: 'task-3',
        title: 'Firmware: Motor Controller CAN-Bus Telemetry Packets',
        description: 'Encode brushless motor encoder positions and temperature telemetry into 1Mbps CAN-FD frames.',
        category: 'Embedded',
        status: 'Open',
        priority: 'Medium',
        rewardTier: 'Tier 3',
        skillsRequired: ['C++', 'CAN-Bus', 'STM32'],
        dueDate: '2026-10-12'
      },
      {
        id: 'task-4',
        title: 'Documentation: Open Hardware Replication & Bill of Materials',
        description: 'Document standard off-the-shelf fasteners, bearings, motor models, and assembly checklist.',
        category: 'Documentation',
        status: 'Open',
        priority: 'Low',
        rewardTier: 'Tier 2',
        skillsRequired: ['Markdown', 'Git', 'BOM Management'],
        dueDate: '2026-10-20'
      }
    ],
    contributors: [
      {
        id: 'c-1',
        name: 'Zaman',
        role: 'Project Lead',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        contributionsCount: 42,
        level: 2,
        joinedDate: 'Mar 2025'
      },
      {
        id: 'c-2',
        name: 'Priya Sharma',
        role: 'AI / Navigation Lead',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        contributionsCount: 28,
        level: 3,
        joinedDate: 'Apr 2025'
      },
      {
        id: 'c-3',
        name: 'Arjun Mehta',
        role: 'Embedded Systems',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        contributionsCount: 19,
        level: 3,
        joinedDate: 'May 2025'
      },
      {
        id: 'c-4',
        name: 'Riya Verma',
        role: 'Mechanical CAD',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
        contributionsCount: 14,
        level: 2,
        joinedDate: 'Jun 2025'
      },
      {
        id: 'c-5',
        name: 'Karan Singh',
        role: 'Computer Vision',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        contributionsCount: 11,
        level: 2,
        joinedDate: 'Jul 2025'
      },
      {
        id: 'c-6',
        name: 'Ananya Rao',
        role: 'Sensor Fusion',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        contributionsCount: 8,
        level: 4,
        joinedDate: 'Aug 2025'
      }
    ],
    files: [
      { id: 'f-1', name: 'autonomous_rover_chassis_cad.step', size: '24.5 MB', type: '3D CAD', updatedAt: 'Yesterday', uploadedBy: 'Riya Verma' },
      { id: 'f-2', name: 'stereoscopic_slam_node.py', size: '42 KB', type: 'CODE', updatedAt: '3 days ago', uploadedBy: 'Zaman' },
      { id: 'f-3', name: 'mainboard_pcb_gerbers_v3.zip', size: '4.8 MB', type: 'PCB', updatedAt: '1 week ago', uploadedBy: 'Arjun Mehta' },
      { id: 'f-4', name: 'field_test_mars_yard_report.pdf', size: '6.2 MB', type: 'REPORT', updatedAt: '2 weeks ago', uploadedBy: 'Zaman' },
      { id: 'f-5', name: 'rover_schematics_revB.kicad_sch', size: '1.9 MB', type: 'SCHEMATIC', updatedAt: '2 weeks ago', uploadedBy: 'Arjun Mehta' }
    ]
  },
  {
    id: 'proj-02',
    code: 'CH-PROJ-PCB-2025',
    title: 'Low-Cost PCB Fabrication',
    tagline: 'Developing an affordable PCB prototyping solution for students.',
    description: 'An open-source desktop milling and chemical etching workstation enabling makers to fabricate rapid double-sided surface mount circuit boards in under 45 minutes.',
    problemStatement: 'International PCB prototyping cycles take 10-14 days and high customs duties, halting academic engineering iterations.',
    objective: 'Enable 6-mil trace width in-house desktop PCB fabrication with open-source toolpath generation.',
    category: 'Hardware',
    stage: 'Open',
    progress: 45,
    owner: {
      name: 'Vikram Patel',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      role: 'Lab Director',
      organization: 'Makerspace Bengaluru'
    },
    location: 'Bengaluru, India',
    timeline: '4 months remaining',
    skillLevel: 'Beginner - Intermediate',
    visibility: 'Open Source',
    isPhysical: true,
    requiredSkills: ['Hardware', 'PCB', 'Manufacturing', 'KiCAD', 'CNC'],
    currentContributors: 5,
    maxContributors: 10,
    openTasksCount: 4,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    views: 3200,
    stars: 82,
    createdAt: '2025-05-12',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-03',
    code: 'CH-PROJ-AGRI-2025',
    title: 'Smart Agriculture System',
    tagline: 'IoT-based monitoring system for precision farming.',
    description: 'Autonomous soil moisture, canopy temperature, and NPK nutrient sensors paired with solar drip irrigation actuators for arid crop yields.',
    problemStatement: 'Over-irrigation in Punjab aquifers has depleted water tables by 4 meters over 5 years while wasting fertilizer runoff.',
    objective: 'Deploy 80 wireless sensor nodes powered by supercapacitors in wheat and mustard farms.',
    category: 'Electronics',
    stage: 'Active',
    progress: 30,
    owner: {
      name: 'Dr. Gurpreet Singh',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      role: 'Agritech Lead',
      organization: 'PAU Ludhiana'
    },
    location: 'Punjab, India',
    timeline: '6 months remaining',
    skillLevel: 'Intermediate',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['IoT', 'Agriculture', 'Sensors', 'LoRaWAN', 'Solar Harvesting'],
    currentContributors: 11,
    maxContributors: 20,
    openTasksCount: 6,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800&auto=format&fit=crop&q=80',
    views: 2980,
    stars: 114,
    createdAt: '2025-04-18',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-04',
    code: 'CH-PROJ-BIONIC-2025',
    title: 'Bionic Hand Prototype',
    tagline: 'Affordable and functional prosthetic hand using 3D printing.',
    description: 'Myoelectric prosthetic with tendon-driven fingers, compliant silicone fingertips, and tactile pressure feedback for amputees.',
    problemStatement: 'Children outgrow expensive medical prosthetics annually, leaving thousands without assistive devices.',
    objective: 'Fabricate modular parametric hands in standard PLA/PETG with interchangeable socket geometry under ₹12,000.',
    category: 'Robotics',
    stage: 'Active',
    progress: 60,
    owner: {
      name: 'BioHeal Labs',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      role: 'Biomechanics Director',
      organization: 'BioHeal Foundation'
    },
    location: 'Hyderabad, India',
    timeline: '3 months remaining',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Healthcare', '3D Printing', 'Design', 'EMG Processing', 'Embedded C'],
    currentContributors: 7,
    maxContributors: 12,
    openTasksCount: 3,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    views: 4120,
    stars: 148,
    createdAt: '2025-03-24',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-05',
    code: 'CH-PROJ-ENERGY-2025',
    title: 'Hybrid Renewable Energy System',
    tagline: 'Integrated solar and wind solution for rural areas.',
    description: 'Micro-scale vertical axis wind turbine coupled with bifacial solar panels and MPPT battery bank designed for coastal and off-grid villages.',
    problemStatement: 'Monsoon coastal conditions cause prolonged solar grid blackouts while wind generation remains underutilized.',
    objective: 'Demonstrate continuous 1.5kW clean power generation throughout tropical storm seasons.',
    category: 'CleanTech',
    stage: 'Open',
    progress: 25,
    owner: {
      name: 'Kavita Chawla',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      role: 'Clean Energy Researcher',
      organization: 'IIT Madras Energy Lab'
    },
    location: 'Chennai, India',
    timeline: '8 months remaining',
    skillLevel: 'All Levels',
    visibility: 'Open Source',
    isPhysical: true,
    requiredSkills: ['Energy', 'Sustainability', 'Hardware', 'Power Electronics', 'Inverter Design'],
    currentContributors: 9,
    maxContributors: 18,
    openTasksCount: 7,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&auto=format&fit=crop&q=80',
    views: 2430,
    stars: 92,
    createdAt: '2025-06-01',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-06',
    code: 'CH-PROJ-NANO-2025',
    title: 'Nano-Material Research',
    tagline: 'Exploring nano-materials for next-gen electronics.',
    description: 'Synthesizing two-dimensional molybdenum disulfide (MoS2) and graphene heterostructures for ultra-low power neuromorphic synaptic transistors.',
    problemStatement: 'Silicon CMOS scaling reaches physical tunneling barriers, requiring 2D atomic semiconductors for sub-1nm gates.',
    objective: 'Publish open dataset of chemical vapor deposition parameters and high-mobility I-V characteristics.',
    category: 'Research',
    stage: 'Active',
    progress: 40,
    owner: {
      name: 'Dr. Meera Iyer',
      avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
      role: 'Principal Investigator',
      organization: 'IISc Materials Science'
    },
    location: 'IIT Delhi, India',
    timeline: '10 months remaining',
    skillLevel: 'Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Research', 'Materials', 'Semiconductor', 'AFM Analysis', 'Cleanroom Protocols'],
    currentContributors: 6,
    maxContributors: 10,
    openTasksCount: 4,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
    views: 3890,
    stars: 165,
    createdAt: '2025-02-14',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-07',
    code: 'CH-PROJ-DRONE-2025',
    title: 'Disaster Relief Drone',
    tagline: 'Drones for disaster mapping and supply delivery.',
    description: 'Long-range VTOL (Vertical Take-off & Landing) autonomous drone payload delivery system engineered for flash floods and Himalayan terrain relief.',
    problemStatement: 'Mountainous landslides cut off road access to remote villages during monsoons, delaying essential medicine delivery.',
    objective: 'Achieve 3kg payload delivery across 40km round-trip in sub-zero alpine conditions with thermal survivor detection.',
    category: 'Hardware',
    stage: 'Active',
    progress: 80,
    owner: {
      name: 'Aarav Singh',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      role: 'Avionics Engineer',
      organization: 'AeroSky Labs'
    },
    location: 'Uttarakhand, India',
    timeline: '1 month remaining',
    skillLevel: 'Intermediate - Advanced',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['Drones', 'Computer Vision', 'Logistics', 'ArduPilot', 'Aerodynamics'],
    currentContributors: 12,
    maxContributors: 15,
    openTasksCount: 2,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
    views: 5120,
    stars: 230,
    createdAt: '2025-01-20',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-08',
    code: 'CH-PROJ-AILRN-2025',
    title: 'AI Learning Platform',
    tagline: 'An open platform for personalized skill development.',
    description: 'Adaptive open-source knowledge graph recommending customized STEM hands-on project pathways based on learner skill gaps and hardware availability.',
    problemStatement: 'Generic online MOOCs have sub-10% completion rates due to lack of physical project integration.',
    objective: 'Generate personalized learning roadmaps tied to real open-hardware repository contributions.',
    category: 'AI / ML',
    stage: 'Open',
    progress: 50,
    owner: {
      name: 'LearnLoop Team',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      role: 'Core Contributors',
      organization: 'LearnLoop'
    },
    location: 'Remote',
    timeline: '5 months remaining',
    skillLevel: 'Beginner - Intermediate',
    visibility: 'Open Source',
    isPhysical: false,
    requiredSkills: ['AI', 'Education', 'Web App', 'React', 'Node.js', 'LLM Tuning'],
    currentContributors: 14,
    maxContributors: 25,
    openTasksCount: 8,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    views: 3450,
    stars: 128,
    createdAt: '2025-05-02',
    tasks: [],
    contributors: [],
    files: []
  },
  {
    id: 'proj-09',
    code: 'CH-PROJ-SORT-2025',
    title: 'AI Based Sorting Arm',
    tagline: 'Computer vision and robotic manipulation for automated factory recycling.',
    description: 'High-speed Delta robot mechanism utilizing RGB-D depth perception and edge neural inference to sort municipal plastic polymers at 90 picks per minute.',
    problemStatement: 'Manual waste segregation exposes workers to hazardous materials while maintaining low throughput and contamination.',
    objective: 'Sort PET, HDPE, and PP plastics with 97% purity using lightweight on-premise vision models.',
    category: 'Robotics',
    stage: 'Active',
    progress: 65,
    owner: {
      name: 'Rakesh Verma',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      role: 'Mechatronics Lead',
      organization: 'TechFab Maharashtra'
    },
    location: 'Pune, India',
    timeline: '3 months remaining',
    skillLevel: 'Intermediate',
    visibility: 'Public',
    isPhysical: true,
    requiredSkills: ['AI', 'Computer Vision', 'Robotics', 'Delta Kinematics', 'YOLOv10'],
    currentContributors: 7,
    maxContributors: 12,
    openTasksCount: 4,
    verified: true,
    coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    views: 3120,
    stars: 141,
    createdAt: '2025-04-10',
    tasks: [],
    contributors: [],
    files: []
  }
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Hardware Intern',
    organization: 'NovaTech Labs',
    orgLogo: '⚡',
    orgType: 'Startup',
    category: 'Paid Internship',
    location: 'Bengaluru, India',
    isRemote: false,
    duration: '3 months',
    difficulty: 'Intermediate',
    rewardTier: 'Tier 3',
    rewardDetails: '₹25,000/mo + Hardware Kit & Lab Access',
    skillsRequired: ['PCB Design', 'KiCAD', 'Soldering', 'Microcontrollers'],
    description: 'Join our avionics and telemetry hardware engineering team prototyping high-reliability power management boards.',
    verificationRequired: 2,
    deadline: '2026-10-15',
    applicantsCount: 34,
    postedDate: '1 day ago'
  },
  {
    id: 'opp-2',
    title: 'Research Assistant',
    organization: 'IIT Research Lab',
    orgLogo: '🔬',
    orgType: 'Research Lab',
    category: 'Research Assistant',
    location: 'Delhi, India',
    isRemote: false,
    duration: '6 months',
    difficulty: 'Advanced',
    rewardTier: 'Tier 4',
    rewardDetails: 'Academic Co-Authorship & Institute Stipend',
    skillsRequired: ['Robotics', 'ROS2', 'Python', 'Kinematics'],
    description: 'Work alongside doctoral candidates on autonomous planetary exploration algorithms and field-testing trials.',
    verificationRequired: 2,
    deadline: '2026-10-20',
    applicantsCount: 48,
    postedDate: '2 days ago'
  },
  {
    id: 'opp-3',
    title: 'PCB Design Contributor',
    organization: 'Open Source Hardware Club',
    orgLogo: '🛠️',
    orgType: 'Open Source',
    category: 'Volunteer',
    location: 'Remote',
    isRemote: true,
    duration: 'Flexible',
    difficulty: 'Beginner',
    rewardTier: 'Tier 2',
    rewardDetails: 'Verified Portfolio Credit & Open Source Badge',
    skillsRequired: ['KiCAD', 'Circuit Design', 'Documentation'],
    description: 'Review and optimize open-source sensor breakout board layouts for community educational kits.',
    verificationRequired: 1,
    deadline: '2026-11-01',
    applicantsCount: 19,
    postedDate: '3 days ago'
  },
  {
    id: 'opp-4',
    title: 'Manufacturing Support',
    organization: 'SkyTech Industries',
    orgLogo: '🏭',
    orgType: 'Business',
    category: 'Project Contribution',
    location: 'Pune, India',
    isRemote: false,
    duration: '2 months',
    difficulty: 'Intermediate',
    rewardTier: 'Tier 3',
    rewardDetails: 'Paid Project Stipend + Industrial CNC Certification',
    skillsRequired: ['CNC Machining', 'CAD/CAM', '3D Printing', 'Quality Assurance'],
    description: 'Assisting small-batch assembly and mechanical tolerance checks for industrial drone chassis production.',
    verificationRequired: 2,
    deadline: '2026-10-30',
    applicantsCount: 22,
    postedDate: '4 days ago'
  }
];

export const MOCK_LEARNING_MODULES: CourseModule[] = [
  {
    id: 'learn-1',
    title: 'AI for Real-World Projects',
    description: 'Practical computer vision, edge inferencing, and multimodal intelligence applied to physical robotics and sensor networks.',
    category: 'AI & ML',
    level: 'Beginner',
    duration: '4 Hours',
    modulesCount: 6,
    enrolledCount: 14200,
    rating: 4.8,
    progress: 75,
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    skillsTaught: ['Computer Vision', 'PyTorch', 'Edge AI', 'Model Deployment'],
    linkedProjectsCount: 24
  },
  {
    id: 'learn-2',
    title: 'PCB Design and Prototyping',
    description: 'From schematic capture to Gerber generation. Master multi-layer PCB design, impedance matching, and DFM using KiCAD 8.',
    category: 'Electronics',
    level: 'Intermediate',
    duration: '6 Hours',
    modulesCount: 8,
    enrolledCount: 9800,
    rating: 4.7,
    progress: 40,
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    skillsTaught: ['KiCAD', 'Routing', 'Design Rules', 'SMT Soldering'],
    linkedProjectsCount: 18
  },
  {
    id: 'learn-3',
    title: 'Robotics and Embedded Systems',
    description: 'Build complete robotic systems from motor control and sensor fusion to ROS2 communication nodes and trajectory planning.',
    category: 'Robotics',
    level: 'Intermediate',
    duration: '8 Hours',
    modulesCount: 10,
    enrolledCount: 12500,
    rating: 4.9,
    progress: 20,
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    skillsTaught: ['ROS2', 'C++', 'Microcontrollers', 'Kinematics', 'Actuators'],
    linkedProjectsCount: 32
  },
  {
    id: 'learn-4',
    title: '3D Modeling & Printing',
    description: 'Design functional mechanical enclosures and structural parts using parametric CAD and slice for industrial additive manufacturing.',
    category: 'Design & CAD',
    level: 'Beginner',
    duration: '4 Hours',
    modulesCount: 5,
    enrolledCount: 8100,
    rating: 4.6,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    skillsTaught: ['SolidWorks', 'Fusion 360', 'FDM Slicing', 'Tolerancing'],
    linkedProjectsCount: 15
  }
];

export const MOCK_LEARNING_PATHS = [
  {
    id: 'path-1',
    title: 'Become a Robotics Developer',
    description: 'Master mechanical design, embedded firmware, sensor fusion, and ROS2 navigation.',
    coursesCount: 6,
    projectsCount: 3,
    enrolledCount: 4200,
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'path-2',
    title: 'AI for Innovators',
    description: 'From foundational deep learning models to on-device edge AI and computer vision.',
    coursesCount: 5,
    projectsCount: 2,
    enrolledCount: 6800,
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'path-3',
    title: 'Hardware Product Design',
    description: 'Take ideas from napkin sketches to functional prototypes, KiCAD boards, and manufacturing.',
    coursesCount: 7,
    projectsCount: 3,
    enrolledCount: 3900,
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'path-4',
    title: 'Research & Publication',
    description: 'Formulate hypotheses, design reproducible lab experiments, and publish peer-reviewed papers.',
    coursesCount: 4,
    projectsCount: 1,
    enrolledCount: 2400,
    thumbnail: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'path-5',
    title: 'Build a Startup',
    description: 'Validate deep-tech ideas, build minimum viable prototypes, find co-founders, and pitch angels.',
    coursesCount: 5,
    projectsCount: 2,
    enrolledCount: 5100,
    thumbnail: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&auto=format&fit=crop&q=80'
  }
];

export const MOCK_FACILITIES: InfrastructureFacility[] = [
  {
    id: 'fac-1',
    name: 'Advanced AI & Robotics Lab',
    type: 'Robotics',
    institution: 'IIT Delhi Innovation Park',
    location: 'Hauz Khas, New Delhi',
    coordinates: { x: 38, y: 28 },
    distance: '5 km away',
    equipment: ['UR5e Collaborative Cobots', 'Stereo Vision Rigs', 'Motion Capture Arena', 'NVIDIA DGX Cluster'],
    capacity: '24 workstations (70% in use)',
    availability: 'Immediate',
    supportedWork: ['Robotics Navigation', 'Computer Vision', 'Deep Learning Inference', 'SLAM Testing'],
    provider: 'IIT Delhi Nanoscale Research Facility',
    hourlyRate: 'Subsidized for verified students (₹150/hr)',
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'fac-2',
    name: 'TinkerHub Makerspace',
    type: '3D Printing',
    institution: 'NIT Trichy Innovation Zone',
    location: 'Tiruchirappalli, Tamil Nadu',
    coordinates: { x: 48, y: 84 },
    distance: '2 km away',
    equipment: ['Industrial FDM 3D Printers', 'Epilog Laser Cutters 120W', 'Desktop CNC Routers', 'Soldering Stations'],
    capacity: '35 open desks',
    availability: 'Immediate',
    supportedWork: ['Rapid Prototyping', 'Chassis Fabrication', 'Laser Cutting', 'Physical Computing'],
    provider: 'NIT Trichy Center for Innovation',
    hourlyRate: 'Free for open-source projects',
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'fac-3',
    name: 'Clean Energy Research Center',
    type: 'Testing & Calibration',
    institution: 'IISc Bengaluru',
    location: 'Malleshwaram, Bengaluru',
    coordinates: { x: 42, y: 72 },
    distance: '8 km away',
    equipment: ['Solar Simulator Class AAA', 'Battery Cycler 64-Channel', 'Environmental Test Chamber (-40°C to 150°C)', 'Impedance Spectrometer'],
    capacity: '12 dedicated test cells',
    availability: 'Waitlist (2 days)',
    supportedWork: ['Renewable Energy', 'Battery Management', 'Solar Testing', 'Extreme Weather Validation'],
    provider: 'IISc Center for Sustainable Tech',
    hourlyRate: '₹200/hr for student teams',
    status: 'Reserved',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'fac-4',
    name: 'Electronics Prototyping Lab',
    type: 'Electronics & PCB',
    institution: 'IIIT Hyderabad',
    location: 'Gachibowli, Hyderabad',
    coordinates: { x: 44, y: 58 },
    distance: '15 km away',
    equipment: ['Pick & Place SMT Machine', '1GHz 4-Channel Oscilloscopes', 'Reflow Oven (8 Zones)', 'Spectrum Analyzer to 6GHz'],
    capacity: '20 high-speed electronic benches',
    availability: 'Immediate',
    supportedWork: ['PCB Fabrication', 'Surface Mount Assembly', 'RF Characterization', 'Firmware Flashing'],
    provider: 'IIIT Smart City Living Lab',
    hourlyRate: '₹120/hr',
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80'
  }
];

export const MOCK_POPULAR_EQUIPMENT = [
  {
    id: 'eq-1',
    name: '3D Printer',
    model: 'Prusa i3 MK4',
    category: 'Additive Manufacturing',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&auto=format&fit=crop&q=80',
    availableUnits: 14,
    locationsCount: 8
  },
  {
    id: 'eq-2',
    name: 'Laser Cutter',
    model: 'Glowforge Pro',
    category: 'Rapid Subtractive',
    image: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=600&auto=format&fit=crop&q=80',
    availableUnits: 9,
    locationsCount: 5
  },
  {
    id: 'eq-3',
    name: 'Robotic Arm',
    model: 'Universal Robots UR5e',
    category: 'Industrial Automation',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&auto=format&fit=crop&q=80',
    availableUnits: 6,
    locationsCount: 3
  },
  {
    id: 'eq-4',
    name: 'CNC Milling Machine',
    model: 'Tormach 1100M',
    category: 'Subtractive Precision',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    availableUnits: 4,
    locationsCount: 4
  }
];

export const MOCK_FEED_POSTS: FeedPost[] = [
  {
    id: 'post-1',
    author: {
      name: 'Zaman',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      handle: '@zaman',
      role: 'Project Lead • Autonomous Rover',
      verificationLevel: 2
    },
    project: {
      id: 'proj-01',
      title: 'Autonomous Rover',
      code: 'CH-PROJ-ROVER-2025',
      progress: 72
    },
    type: 'PROJECT UPDATE',
    title: 'Autonomous Rover - Field Testing Complete! 🚀',
    content: 'Just concluded a full day of terrain navigation trials in the Delhi ridge quarry sandpit. Our stereoscopic SLAM node handled severe 35-degree gravel gradients without wheel slippage or motor stall. Huge thanks to Priya Sharma and Arjun Mehta for refining the CAN-bus motor timing!',
    mediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80',
    skillsUsed: ['Robotics', 'Embedded', 'FieldTesting', 'Innovation'],
    task: 'Stereoscopic Depth Map SLAM Tuning',
    contributionStatus: 'Verified',
    likes: 184,
    comments: 29,
    shares: 42,
    collaboratorsInterested: 12,
    timestamp: '2h ago in #Robotics',
    isLiked: true
  },
  {
    id: 'post-2',
    author: {
      name: 'Priya Sharma',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      handle: '@priyasharma',
      role: 'Hardware Engineer at AgriMesh',
      verificationLevel: 3
    },
    type: 'RESEARCH PAPER',
    title: 'New Research on Flexible Electronics & Wearable Bio-Sensors',
    content: 'We synthesized ultra-thin polyimide substrates supporting silver-nanoparticle traces that endure over 10,000 bend cycles with zero impedance loss. Ideal for smart epidermal wearables and agricultural leaf sensors.',
    mediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1000&auto=format&fit=crop&q=80',
    skillsUsed: ['Research', 'FlexibleElectronics', 'Healthcare', 'IoT'],
    contributionStatus: 'Verified',
    likes: 215,
    comments: 18,
    shares: 37,
    collaboratorsInterested: 9,
    timestamp: '5h ago in #Research',
    isLiked: false
  },
  {
    id: 'post-3',
    author: {
      name: 'Aarav Singh',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      handle: '@aarav_mech',
      role: 'Mechatronics Engineer',
      verificationLevel: 3
    },
    project: {
      id: 'proj-04',
      title: 'Bionic Hand Prototype',
      code: 'CH-PROJ-BIONIC-2025',
      progress: 60
    },
    type: 'TECHNICAL WORK',
    title: '3D Printed Robotic Arm v2.0 Assembly & Testing',
    content: 'Upgraded our 6-DOF robotic manipulator with harmonic-drive cycloidal gears and integrated magnetic rotary encoders. Repeatability is now under 0.2mm. STEP files and firmware are available in our open workspace!',
    mediaUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1000&auto=format&fit=crop&q=80',
    skillsUsed: ['3DPrinting', 'Robotics', 'OpenSource', 'Hardware'],
    task: 'Arm Joint Kinematics Calibration',
    contributionStatus: 'Verified',
    likes: 310,
    comments: 42,
    shares: 65,
    collaboratorsInterested: 18,
    timestamp: '1d ago in #Hardware',
    isLiked: false
  },
  {
    id: 'post-4',
    author: {
      name: 'Rohit Mehta',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      handle: '@rohit_pcb',
      role: 'Hardware Designer',
      verificationLevel: 2
    },
    type: 'PROJECT UPDATE',
    title: 'Best PCB Manufacturer in India for 4-Layer Controlled Impedance?',
    content: 'We are manufacturing high-speed USB 3.0 and differential RF tracks for our open satellite receiver. Looking for fabricators offering quick turnarounds under 5 days in Bengaluru or Pune with ENIG finish.',
    mediaUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1000&auto=format&fit=crop&q=80',
    skillsUsed: ['PCB', 'Manufacturing', 'Hardware', 'KiCAD'],
    likes: 95,
    comments: 34,
    shares: 11,
    collaboratorsInterested: 4,
    timestamp: '1d ago in #PCB',
    isLiked: false
  },
  {
    id: 'post-5',
    author: {
      name: 'Sneha Iyer',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      handle: '@sneha_stem',
      role: 'STEM Educator & Community Lead',
      verificationLevel: 3
    },
    type: 'TECHNICAL WORK',
    title: 'Volunteers Needed for Rural STEM Workshop in Himachal',
    content: 'CraftHub members are traveling to Shimla next month to distribute 50 open-hardware microcontroller learning kits to high-school students. If you want to mentor hands-on workshops, drop a comment below!',
    mediaUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1000&auto=format&fit=crop&q=80',
    skillsUsed: ['Education', 'STEM', 'Community', 'Mentorship'],
    likes: 188,
    comments: 27,
    shares: 39,
    collaboratorsInterested: 15,
    timestamp: '2d ago in #Community',
    isLiked: true
  }
];

export const MOCK_STARTUPS: StartupEntity[] = [
  {
    id: 'st-1',
    name: 'AgriSense',
    tagline: 'Precision AI-powered soil and crop monitoring drone network.',
    founder: 'Siddharth Rao',
    stage: 'Early Stage',
    category: 'AgriTech / Sustainability',
    teamSize: 8,
    problem: 'Farmers lose up to 40% of seasonal yield to undetected fungal leaf blights.',
    solution: 'Autonomous multi-spectral drones and IoT soil sensors providing actionable plant health maps.',
    openRoles: 3,
    infrastructureNeeded: ['Testing Farm (5 acres)', 'Electronics Assembly Cleanroom', 'RF Test Bed'],
    fundingStatus: 'Seed Stage (₹1.8 Cr Raised)',
    logo: '🌱',
    location: 'Punjab / Bengaluru',
    coverImage: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'st-2',
    name: 'MediMind',
    tagline: 'Predictive health insights and non-invasive biometric monitoring smartwatch.',
    founder: 'Dr. Ananya Rao',
    stage: 'Prototype',
    category: 'HealthTech / AI',
    teamSize: 6,
    problem: 'Cardiovascular arrhythmia spikes occur silently outside clinical diagnostic visits.',
    solution: 'Continuous photoplethysmography and edge ECG neural models warning patients 30 minutes in advance.',
    openRoles: 2,
    infrastructureNeeded: ['Biocompatible 3D Printing', 'Clinical Calibration Testbed'],
    fundingStatus: 'Pre-Seed (₹60 Lakh)',
    logo: '🩺',
    location: 'Hyderabad',
    coverImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'st-3',
    name: 'ReCircle',
    tagline: 'Smart reverse vending and municipal automated recycling bins.',
    founder: 'Rohan Mehta',
    stage: 'Growth',
    category: 'CleanTech / IoT',
    teamSize: 12,
    problem: '90% of discarded plastic bottles never enter municipal recycling loops due to lack of incentive.',
    solution: 'AI smart bin identifying plastic polymer types and instantly crediting digital UPI rewards to citizens.',
    openRoles: 4,
    infrastructureNeeded: ['Sheet Metal Fabrication', 'CNC Milling'],
    fundingStatus: 'Series A (₹5.2 Cr Raised)',
    logo: '♻️',
    location: 'Mumbai / Pune',
    coverImage: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'st-4',
    name: 'LearnLoop',
    tagline: 'Adaptive AI skill development platform for engineering students.',
    founder: 'Karan Verma',
    stage: 'Early Stage',
    category: 'EdTech / AI',
    teamSize: 5,
    problem: 'Engineering graduates face an 80% employable skills mismatch with hardware industries.',
    solution: 'Project-first interactive curriculum paired with open hardware kit simulations.',
    openRoles: 2,
    infrastructureNeeded: ['Cloud Compute', 'High-Performance Hosting'],
    fundingStatus: 'Seed Stage (₹1.2 Cr)',
    logo: '🎓',
    location: 'Bengaluru',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'st-5',
    name: 'RoboKart',
    tagline: 'Autonomous last-mile delivery robot for universities and hospitals.',
    founder: 'Rakesh Verma',
    stage: 'Prototype',
    category: 'Robotics / Logistics',
    teamSize: 7,
    problem: 'Intra-campus medicine and logistics movement requires manual courier delivery.',
    solution: '4-wheel drive lidar-equipped autonomous delivery rover with tamper-proof digital compartments.',
    openRoles: 3,
    infrastructureNeeded: ['Robotics Test Track', 'SMT PCB Assembly'],
    fundingStatus: 'Bootstrapped / Grant (₹40 Lakh)',
    logo: '🤖',
    location: 'Delhi',
    coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80'
  }
];

export const MOCK_BUSINESSES: BusinessEntity[] = [
  {
    id: 'biz-1',
    name: 'Tesla India',
    tagline: 'Accelerating the world\'s transition to sustainable energy and electric mobility.',
    category: 'Automotive / Clean Energy',
    location: 'Bengaluru, India',
    type: 'Global Player',
    tags: ['Electric Vehicles', 'Battery Tech', 'Autonomous Driving', 'Renewables'],
    coverImage: 'https://images.unsplash.com/photo-1538392250201-141104695421?w=800&auto=format&fit=crop&q=80',
    logo: '⚡',
    description: 'Partnering with academic institutions and hardware startups on EV battery thermal management, charging infrastructure, and power electronics.',
    openProjects: 8,
    openRoles: 14,
    partnershipOpportunities: 5
  },
  {
    id: 'biz-2',
    name: 'L&T Technology Services',
    tagline: 'Engineering the future with intelligent automation, smart factories, and IoT.',
    category: 'Engineering & Automation',
    location: 'Chennai / Mumbai, India',
    type: 'Industry Leader',
    tags: ['Robotics', 'Industrial IoT', 'Digital Twins', 'Embedded Systems'],
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    logo: '🏗️',
    description: 'Collaborating on deep-tech hardware incubators, offering lab access and prototype testing for industrial robotic arms and telematics.',
    openProjects: 12,
    openRoles: 26,
    partnershipOpportunities: 9
  },
  {
    id: 'biz-3',
    name: 'SELCO Foundation',
    tagline: 'Social innovations using sustainable solar energy for underserved livelihoods.',
    category: 'Renewable Energy / Social Impact',
    location: 'Bengaluru, India',
    type: 'Social Enterprise',
    tags: ['Solar Power', 'Grassroots Innovation', 'Healthcare Tech', 'Agri-Processing'],
    coverImage: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&auto=format&fit=crop&q=80',
    logo: '☀️',
    description: 'Funding and prototyping decentralized clean energy equipment for rural health centers, micro-enterprises, and agri-cold storage.',
    openProjects: 6,
    openRoles: 8,
    partnershipOpportunities: 7
  },
  {
    id: 'biz-4',
    name: 'Infosys Innovation Network',
    tagline: 'Navigating your next with enterprise digital transformation and AI ecosystem.',
    category: 'IT Services & AI',
    location: 'Bengaluru / Pune, India',
    type: 'Industry Leader',
    tags: ['Enterprise AI', 'Cloud', 'Cybersecurity', 'Open Innovation'],
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    logo: '🌐',
    description: 'Connecting enterprise clients with promising academic research and deep-tech startup prototypes for enterprise deployment.',
    openProjects: 15,
    openRoles: 32,
    partnershipOpportunities: 12
  }
];

export const MOCK_RESEARCH_TOPICS = [
  {
    id: 'res-top-1',
    name: 'Artificial Intelligence',
    papersCount: '120K+ papers',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    activeResearchers: '14,200',
    growth: '+28% this year'
  },
  {
    id: 'res-top-2',
    name: 'Climate Change & Clean Energy',
    papersCount: '85K+ papers',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600&auto=format&fit=crop&q=80',
    activeResearchers: '9,800',
    growth: '+35% this year'
  },
  {
    id: 'res-top-3',
    name: 'Biomedical Engineering',
    papersCount: '72K+ papers',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&auto=format&fit=crop&q=80',
    activeResearchers: '8,400',
    growth: '+19% this year'
  },
  {
    id: 'res-top-4',
    name: 'Quantum Computing',
    papersCount: '68K+ papers',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    activeResearchers: '6,100',
    growth: '+42% this year'
  },
  {
    id: 'res-top-5',
    name: 'Space Exploration',
    papersCount: '54K+ papers',
    image: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=600&auto=format&fit=crop&q=80',
    activeResearchers: '5,300',
    growth: '+24% this year'
  },
  {
    id: 'res-top-6',
    name: 'Sustainable Technologies',
    papersCount: '49K+ papers',
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&auto=format&fit=crop&q=80',
    activeResearchers: '7,200',
    growth: '+31% this year'
  }
];

export const MOCK_RESEARCH_PAPERS: ResearchPaper[] = [
  {
    id: 'paper-1',
    title: 'A Unified Framework for Multimodal Learning in Real-World Robotics',
    category: 'AI & ML',
    journal: 'arXiv / IEEE Transactions on Robotics',
    year: 2025,
    authors: ['Dr. Ananya Rao', 'Zaman', 'Priya Sharma', 'K. Murthy'],
    abstract: 'We introduce a unified vision-language-action foundation model optimized for sub-10W edge compute in autonomous rovers navigating dynamic unstructured planetary and terrestrial environments.',
    citations: 142,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    doi: '10.1109/TRO.2025.0189',
    pdfUrl: '#'
  },
  {
    id: 'paper-2',
    title: 'Scalable Solutions for Carbon-Neutral Energy Systems in Arid Micro-Grids',
    category: 'Sustainability',
    journal: 'Nature Energy / IEEE GreenTech',
    year: 2025,
    authors: ['Dr. Meera Iyer', 'Kavita Chawla', 'S. Gupta'],
    abstract: 'Experimental validation of hybrid bifacial photovoltaic and vertical-axis aerodynamic kinetic capture architectures under high thermal ambient degradation.',
    citations: 98,
    coverImage: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600&auto=format&fit=crop&q=80',
    doi: '10.1038/s41560-025-0142',
    pdfUrl: '#'
  },
  {
    id: 'paper-3',
    title: 'Next-Generation Myoelectric Signal Acquisition with Dry Carbon Electrodes',
    category: 'Healthcare',
    journal: 'Biomedical Microdevices',
    year: 2024,
    authors: ['Dr. R. Bannerjee', 'BioHeal Research Team'],
    abstract: 'Demonstrating 98.4% pattern recognition accuracy for pediatric bionic upper-limb control with 12-hour continuous skin adherence and sweat compensation.',
    citations: 76,
    coverImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&auto=format&fit=crop&q=80',
    doi: '10.1007/s10544-024-00712',
    pdfUrl: '#'
  }
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'project',
    title: 'New Contributor Joined',
    description: 'Karan Singh joined your Autonomous Rover project team as Computer Vision Specialist.',
    timestamp: '15m ago',
    isRead: false
  },
  {
    id: 'notif-2',
    type: 'contribution',
    title: 'Contribution Verified!',
    description: 'Your contribution "Stereoscopic Depth Map SLAM Tuning" has been verified and awarded Tier 4.',
    timestamp: '2h ago',
    isRead: false
  },
  {
    id: 'notif-3',
    type: 'opportunity',
    title: 'New Hardware Opportunity',
    description: 'NovaTech Labs posted a new paid hardware internship matching your skills.',
    timestamp: '1d ago',
    isRead: true
  },
  {
    id: 'notif-4',
    type: 'verification',
    title: 'Trust Level 2 Verified',
    description: 'Your academic affiliation with IIT Delhi has been verified by the institute coordinator.',
    timestamp: '3d ago',
    isRead: true
  }
];
